/*
 * multi/_all.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/multi/_all.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     55   Upstream files: 26
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Multi_AttackSimulation_Blindspot.yar ----
rule Multi_AttackSimulation_Blindspot_d93f54c5 {
    meta:
        author = "Elastic Security"
        id = "d93f54c5-6574-4999-a3c0-39ef688b28dc"
        fingerprint = "4ec38f841aa4dfe32b1f6b6cd2e361c7298839ef1e983061cb90827135f34a58"
        creation_date = "2022-05-23"
        last_modified = "2022-08-16"
        threat_name = "Multi.AttackSimulation.Blindspot"
        severity = 1
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "\\\\.\\pipe\\blindspot-%d."
    condition:
        all of them
}

// ---- Multi_Cryptominer_Xmrig.yar ----
rule Multi_Cryptominer_Xmrig_f9516741 {
    meta:
        author = "Elastic Security"
        id = "f9516741-aac1-4c67-ad63-3d222814864e"
        fingerprint = "14eef95b5a008e644c2fe2d600c1a883d018c1ab085f4496a3e2211329362d31"
        creation_date = "2025-02-21"
        last_modified = "2025-03-07"
        threat_name = "Multi.Cryptominer.Xmrig"
        reference_sample = "104f839b5da7bd77804ca5ec252d78dccb52800a2ef4fd1179db6deb764af42f"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str_1 = "no valid configuration found, try https://xmrig.com/wizard"
        $str_2 = "xmrig-"
        $str_3 = "XMRig "
        $str_4 = "--donate-level=N"
        $str_5 = "--coin=COIN"
        $str_6 = "--algo=ALGO"
        $str_7 = "hwloc topology successfully exported to \"%s\"\n"
    condition:
        6 of them
}

// ---- Multi_EICAR.yar ----
rule Multi_EICAR_ac8f42d6 {
    meta:
        author = "Elastic Security"
        id = "ac8f42d6-52da-46ec-8db1-5a5f69222a38"
        fingerprint = "bb0e0bdf70ec65d98f652e2428e3567013d5413f2725a2905b372fd18da8b9dd"
        creation_date = "2021-01-21"
        last_modified = "2022-01-13"
        threat_name = "Multi.EICAR.Not-a-virus"
        severity = 1
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*" ascii fullword
    condition:
        all of them
}

// ---- Multi_Generic_Threat.yar ----
rule Multi_Generic_Threat_19854dc2 {
    meta:
        author = "Elastic Security"
        id = "19854dc2-a568-4f6c-bd47-bcae9976c66f"
        fingerprint = "64d3803490fa71f720678ca2989cc698ea9b1a398d02d6d671fa01e0ff42f8b5"
        creation_date = "2024-02-21"
        last_modified = "2024-06-12"
        threat_name = "Multi.Generic.Threat"
        reference_sample = "be216fa9cbf0b64d769d1e8ecddcfc3319c7ca8e610e438dcdfefc491730d208"
        severity = 50
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = { 26 2A 73 74 72 75 63 74 20 7B 20 45 6E 74 72 79 53 61 6C 74 20 5B 5D 75 69 6E 74 38 3B 20 4C 65 6E 20 69 6E 74 20 7D }
    condition:
        all of them
}

// ---- Multi_Hacktool_Gsocket.yar ----
rule Multi_Hacktool_Gsocket_761d3a0f {
    meta:
        author = "Elastic Security"
        id = "761d3a0f-e2e8-4a8a-99f6-7356555a517d"
        fingerprint = "e4426c5faa5775bcfdfbe01c3d6a2b4042aa9bf942883b104c241d0734b272c9"
        creation_date = "2024-09-20"
        last_modified = "2024-11-04"
        threat_name = "Multi.Hacktool.Gsocket"
        reference_sample = "193efd61ae10f286d06390968537fa85e4df40995fd424d1afe426c089d172ab"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str1 = "gsocket: gs_funcs not found"
        $str2 = "/share/gsocket/gs_funcs"
        $str3 = "$GSOCKET_ARGS"
        $str4 = "GSOCKET_SECRET"
        $str5 = "GS_HIJACK_PORTS"
        $str6 = "sftp -D gs-netcat"
        $str7 = "GS_NETCAT_BIN"
        $str8 = "GSOCKET_NO_GREETINGS"
        $str9 = "GS-NETCAT(1)"
        $str10 = "GSOCKET_SOCKS_IP"
        $str11 = "GSOCKET_SOCKS_PORT"
        $str12 = "gsocket(1)"
        $str13 = "gs-sftp(1)"
        $str14 = "gs-mount(1)"
    condition:
        3 of them
}

// ---- Multi_Hacktool_LinPEAS_ng.yar ----
rule Multi_Hacktool_LinPEAS_ng_19e3957f {
    meta:
        author = "Elastic Security"
        id = "19e3957f-8f44-47e1-abf8-a40de645594e"
        fingerprint = "c2e952348ce89a802cedcb089bb1306d3f8f077262753133a35b7a18f8711ba8"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the systen information module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $cve_0 = "CVEs Check" base64
        $cve_1 = "Vulnerable to CVE-2021-4034" base64
        $cve_2 = "Vulnerable to CVE-2021-3560" base64
        $cve_3 = "Potentially Vulnerable to CVE-2022-0847" base64
        $cve_4 = "Potentially Vulnerable to CVE-2022-2588" base64
        $cpu_0 = "Any sd*/disk* disk in /dev?" base64
        $cpu_1 = "$(command -v diskutil)" base64
        $cpu_2 = "Mounted disks information" base64
        $cpu_3 = "$(command -v smbutil)" base64
        $protections_0 = "grsecurity present?" base64
        $protections_1 = "AppArmor enabled?" base64
        $protections_2 = "User namespace?" base64
        $protections_3 = "XProtectPlistConfigData" base64
    condition:
        (2 of ($cve_*) and 2 of ($cpu_*) and 2 of ($protections_*))
}

rule Multi_Hacktool_LinPEAS_ng_f3ab706d {
    meta:
        author = "Elastic Security"
        id = "f3ab706d-1ad4-4ff2-a461-f877c7990dbb"
        fingerprint = "a41a8ff83d1c94b63fb1ecbeded1e54b7d93fb4698ed8dda01b122d1f328de36"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the systen information module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $cve_0 = "CVEs Check"
        $cve_1 = "Vulnerable to CVE-2021-4034"
        $cve_2 = "Vulnerable to CVE-2021-3560"
        $cve_3 = "Potentially Vulnerable to CVE-2022-0847"
        $cve_4 = "Potentially Vulnerable to CVE-2022-2588"
        $cpu_0 = "Any sd*/disk* disk in /dev?"
        $cpu_1 = "$(command -v diskutil)"
        $cpu_2 = "Mounted disks information"
        $cpu_3 = "$(command -v smbutil)"
        $protections_0 = "grsecurity present?"
        $protections_1 = "AppArmor enabled?"
        $protections_2 = "User namespace?"
        $protections_3 = "XProtectPlistConfigData"
    condition:
        (2 of ($cve_*) and 2 of ($cpu_*) and 2 of ($protections_*))
}

rule Multi_Hacktool_LinPEAS_ng_25b07260 {
    meta:
        author = "Elastic Security"
        id = "25b07260-68ab-4b69-a6bb-a4056014329b"
        fingerprint = "0ec6241c4dba1e806c654056257fce7ddd67a4b2cd36d3e19a2c486b5befb7aa"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the container module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $container_0 = "find / -maxdepth 3 -name '*dockerenv*'" base64
        $container_1 = "/kubepod" base64
        $container_2 = "container=podman" base64
        $container_3 = "$(grep -a 'container=' /proc/1/environ" base64
        $container_4 = "You have write permissions over interesting socket" base64
        $container_5 = "Am I Containered?" base64
        $container_6 = "release_agent breakout" base64
        $container_7 = "DoS via panic_" base64
        $container_8 = "Container Capabilities" base64
        $container_9 = "$(command -v capsh)" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_fd5b32cf {
    meta:
        author = "Elastic Security"
        id = "fd5b32cf-b96c-41a1-8119-5a688a1e2ebf"
        fingerprint = "d19f8c7ed050f6c45e613aa70aa5ddd1dc0b7a7d1309d31bc2b5eb969fff6868"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the container module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $container_0 = "find / -maxdepth 3 -name '*dockerenv*'"
        $container_1 = "/kubepod"
        $container_2 = "container=podman"
        $container_3 = "$(grep -a 'container=' /proc/1/environ"
        $container_4 = "You have write permissions over interesting socket"
        $container_5 = "Am I Containered?"
        $container_6 = "release_agent breakout"
        $container_7 = "DoS via panic_"
        $container_8 = "Container Capabilities"
        $container_9 = "$(command -v capsh)"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_d233c491 {
    meta:
        author = "Elastic Security"
        id = "d233c491-d506-49d4-958d-a13ef77fcc71"
        fingerprint = "b6a805f34fb1b7847c1d1180f8c43742aadfa4f9667ad590d3266b69cfde7419"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the cloud module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $cloud_0 = "/devstorage.read_only|/logging.write"
        $cloud_1 = "/monitoring|/servicecontrol|/service.management.readonly"
        $cloud_2 = "grep -q metadata.google.internal /etc/hosts"
        $cloud_3 = "Google Cloud Platform?"
        $cloud_4 = "AWS ECS?"
        $cloud_5 = "Project-ID:"
        $cloud_6 = "OSLogin users:"
        $cloud_7 = "Instance Image:"
        $cloud_8 = "X-aws-ec2-metadata-token:"
        $cloud_9 = "AWS Lambda Enumeration"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_1eb10406 {
    meta:
        author = "Elastic Security"
        id = "1eb10406-aed8-4411-9b6a-5e9cada72c29"
        fingerprint = "d48658714fdab4127535a91ee883e9d0443ed46b6d4c9ff88543cb9f5e940462"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the cloud module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $cloud_0 = "/devstorage.read_only|/logging.write" base64
        $cloud_1 = "/monitoring|/servicecontrol|/service.management.readonly" base64
        $cloud_2 = "grep -q metadata.google.internal /etc/hosts" base64
        $cloud_3 = "Google Cloud Platform?" base64
        $cloud_4 = "AWS ECS?" base64
        $cloud_5 = "Project-ID:" base64
        $cloud_6 = "OSLogin users:" base64
        $cloud_7 = "Instance Image:" base64
        $cloud_8 = "X-aws-ec2-metadata-token:" base64
        $cloud_9 = "AWS Lambda Enumeration" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_46488ab2 {
    meta:
        author = "Elastic Security"
        id = "46488ab2-093f-4371-b806-00e1df5c144e"
        fingerprint = "d12007aa8b6ad1dea30a46fb2b3d39b3a77ef18f6a2ecf6756a6a997e22ccb05"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Processes & Cron & Services & Timers module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $cron_0 = "Looks like ps is not finding processes"
        $cron_1 = "(ps fauxwww || ps auxwww | sort ) 2>/dev/null | grep -v \"\\[\" | grep -v \"%CPU\""
        $cron_2 = "/dev/null | grep CapEff | awk"
        $cron_3 = "awk '!x[$0]++' 2>/dev/null | grep -v \" root root \""
        $cron_4 = "Files opened by processes belonging to other users"
        $cron_5 = "gdm-password process found (dump creds from memory as root)"
        $cron_6 = "-name \"cron*\" -or -name \"anacron\" -or -name \"anacrontab\""
        $cron_7 = "/Library/LaunchDaemons/MonitorHelper.plist ProgramArguments"
        $cron_8 = "SPStartupItemDataType"
        $cron_9 = "Unix Sockets Listening"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_709a480d {
    meta:
        author = "Elastic Security"
        id = "709a480d-f797-4ad0-a67b-6e4b814ffc18"
        fingerprint = "06af5a1d00998d44113c69b5bcf494bbda52ffc63b1013681d46d2122545cded"
        creation_date = "2022-12-21"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Processes & Cron & Services & Timers module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $cron_0 = "Looks like ps is not finding processes" base64
        $cron_1 = "(ps fauxwww || ps auxwww | sort ) 2>/dev/null | grep -v \"\\[\" | grep -v \"%CPU\"" base64
        $cron_2 = "/dev/null | grep CapEff | awk" base64
        $cron_3 = "awk '!x[$0]++' 2>/dev/null | grep -v \" root root \"" base64
        $cron_4 = "Files opened by processes belonging to other users" base64
        $cron_5 = "gdm-password process found (dump creds from memory as root)" base64
        $cron_6 = "-name \"cron*\" -or -name \"anacron\" -or -name \"anacrontab\"" base64
        $cron_7 = "/Library/LaunchDaemons/MonitorHelper.plist ProgramArguments" base64
        $cron_8 = "SPStartupItemDataType" base64
        $cron_9 = "Unix Sockets Listening" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_f9a55fb7 {
    meta:
        author = "Elastic Security"
        id = "f9a55fb7-e457-4b39-943d-a4f99d3a93bf"
        fingerprint = "ffbb559253e242fed1881027e59519a5debe1095237d6efcac5604dd4ac2d2c5"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Network info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $network_0 = "Hostname, hosts and DNS"
        $network_1 = "Networks and neighbours"
        $network_2 = "(route || ip n || cat /proc/net/route)"
        $network_3 = "networksetup -listallhardwareports"
        $network_4 = "timeout 1 tcpdump >/dev/null"
        $network_5 = "[-] No ifconfig or ip commands"
        $network_6 = "$(netstat -na | grep LISTEN | grep tcp46 | grep \"*.3283\" | wc -l);"
        $network_7 = "The following services are OFF if"
        $network_8 = "s,Password|Authorization Name.*"
        $network_9 = "host.docker.internal"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_4c86542f {
    meta:
        author = "Elastic Security"
        id = "4c86542f-ca54-4bdb-a91a-faee83a0e7ac"
        fingerprint = "b2d75cc3f187a00b85c092dc683e9efee6f116f02e1cbc5296402f42fd328436"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Network info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $network_0 = "Hostname, hosts and DNS" base64
        $network_1 = "Networks and neighbours" base64
        $network_2 = "(route || ip n || cat /proc/net/route)" base64
        $network_3 = "networksetup -listallhardwareports" base64
        $network_4 = "timeout 1 tcpdump >/dev/null" base64
        $network_5 = "[-] No ifconfig or ip commands" base64
        $network_6 = "$(netstat -na | grep LISTEN | grep tcp46 | grep \"*.3283\" | wc -l);" base64
        $network_7 = "The following services are OFF if" base64
        $network_8 = "s,Password|Authorization Name.*" base64
        $network_9 = "host.docker.internal" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_62eff03d {
    meta:
        author = "Elastic Security"
        id = "62eff03d-146c-411d-9ee4-418ef94e4003"
        fingerprint = "784fa26c75dbb9deecfacf2098147554706b1c40ab84aa625bc8c8df84fc7cf5"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the User info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $user_0 = "Current user Login and Logout hooks"
        $user_1 = "/var/db/SystemKey"
        $user_2 = "Do I have PGP keys?"
        $user_3 = "$(xclip -o -selection clipboard"
        $user_4 = "timeout 1 sudo -S -l"
        $user_5 = "You can create a file in /etc/sudoers.d/"
        $user_6 = "The escalation didn't work..."
        $user_7 = "$(command -v doas)"
        $user_8 = "UserShell RealName RecordName Password NFSHomeDirectory"
        $user_9 = "^PASS_MAX_DAYS\\|^PASS_MIN_DAYS\\|^PASS_WARN_AGE\\|^ENCRYPT_METHOD"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_3ca885bf {
    meta:
        author = "Elastic Security"
        id = "3ca885bf-c737-4df7-a818-9cdeb49560a4"
        fingerprint = "1817bb75c9ce29ef72a6cdd2fd1d2c568b59f5d180ae7197a00d30f8af070bd4"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the User info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $user_0 = "Current user Login and Logout hooks" base64
        $user_1 = "/var/db/SystemKey" base64
        $user_2 = "Do I have PGP keys?" base64
        $user_3 = "$(xclip -o -selection clipboard" base64
        $user_4 = "timeout 1 sudo -S -l" base64
        $user_5 = "You can create a file in /etc/sudoers.d/" base64
        $user_6 = "The escalation didn't work..." base64
        $user_7 = "$(command -v doas)" base64
        $user_8 = "UserShell RealName RecordName Password NFSHomeDirectory" base64
        $user_9 = "^PASS_MAX_DAYS\\|^PASS_MIN_DAYS\\|^PASS_WARN_AGE\\|^ENCRYPT_METHOD" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_1aa3948b {
    meta:
        author = "Elastic Security"
        id = "1aa3948b-a742-40d1-9f06-7f33260206a7"
        fingerprint = "4b2367262369a0dfe1320e9d4f60a7736c47ef6cefab3966561d8746605ee14f"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Software info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $software_0 = "Installed Compilers"
        $software_1 = "$(command -v pkg 2>/dev/null)"
        $software_2 = "$(command -v mysqladmin)"
        $software_3 = "MySQL version"
        $software_4 = "SELECT User,Host,authentication_string FROM"
        $software_5 = "Some certificates were found (out limited):"
        $software_6 = "keyinfo --list"
        $software_7 = "You could use SSSDKCMExtractor to"
        $software_8 = "LS_USER\\|LS_GROUP"
        $software_9 = "Searching tmux sessions"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_3e7102db {
    meta:
        author = "Elastic Security"
        id = "3e7102db-69e1-45f1-8258-7a1a40e95e45"
        fingerprint = "098396bdcd0b0f83d8064ec4bd26974abdcf5b1d5bb2abd0ef748cf788c5526e"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Software info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $software_0 = "Installed Compilers" base64
        $software_1 = "$(command -v pkg 2>/dev/null)" base64
        $software_2 = "$(command -v mysqladmin)" base64
        $software_3 = "MySQL version" base64
        $software_4 = "SELECT User,Host,authentication_string FROM" base64
        $software_5 = "Some certificates were found (out limited):" base64
        $software_6 = "keyinfo --list" base64
        $software_7 = "You could use SSSDKCMExtractor to" base64
        $software_8 = "LS_USER\\|LS_GROUP" base64
        $software_9 = "Searching tmux sessions" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_a5688824 {
    meta:
        author = "Elastic Security"
        id = "a5688824-9b13-4497-bce7-80362d68a4d5"
        fingerprint = "ae86f4b5040f667b0801ef771a20ffe89543d26935e0ed00f4e8827a7ad2b95a"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Files info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $files_0 = "You have write privileges over"
        $files_1 = "-perm -4000 -type f ! -path"
        $files_2 = "You own the SUID file:"
        $files_3 = "(Unknown SUID binary!)"
        $files_4 = "open|access|no such file"
        $files_5 = "Checking misconfigurations of"
        $files_6 = "$(command -v capsh)"
        $files_7 = "Current env capabilities:"
        $files_8 = "find $HOMESEARCH -user root 2>/dev/null"
        $files_9 = "find /var/mail/ /var/spool/mail/ /private/var/mail -type f -ls"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_ad70184f {
    meta:
        author = "Elastic Security"
        id = "ad70184f-4f91-4eb4-9efc-6afd4058e432"
        fingerprint = "3ee469f99797ad0de08abd89fa6634a464b26894023a45abf8d7f8f0e758e7f3"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Files info module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $files_0 = "You have write privileges over" base64
        $files_1 = "-perm -4000 -type f ! -path" base64
        $files_2 = "You own the SUID file:" base64
        $files_3 = "(Unknown SUID binary!)" base64
        $files_4 = "open|access|no such file" base64
        $files_5 = "Checking misconfigurations of" base64
        $files_6 = "$(command -v capsh)" base64
        $files_7 = "Current env capabilities:" base64
        $files_8 = "find $HOMESEARCH -user root 2>/dev/null" base64
        $files_9 = "find /var/mail/ /var/spool/mail/ /private/var/mail -type f -ls" base64
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_acc02df3 {
    meta:
        author = "Elastic Security"
        id = "acc02df3-8a22-4fe7-83ec-6810b7933d7a"
        fingerprint = "f55005da8a884e05627a511d8aa065ffdac40a947293a95bd754eda268e407c6"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Base module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "cc3e69418622499a21248c762373642eb2a2b1073767f22f0dd0f65d0def94a5"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $base_0 = "$(printf '\\033')"
        $base_1 = "Enumerate and search Privilege Escalation vectors."
        $base_2 = "grep -c processor /proc/cpuinfo"
        $base_3 = "Do you like PEASS?"
        $base_4 = "RED/YELLOW: 95% a PE vector"
        $base_5 = "\\(root\\)|\\(shadow\\)|\\(admin\\)|\\(video\\)|\\(adm\\)|\\(wheel\\)|\\(auth\\)"
        $base_6 = "peass{SUIDVB1_HERE}"
        $base_7 = "file|free|main|more|read|split|write"
        $base_8 = "cap_sys_admin:mount|python"
        $base_9 = "timeout 1 su $(whoami) -c whoami"
    condition:
        5 of them
}

rule Multi_Hacktool_LinPEAS_ng_02c12676 {
    meta:
        author = "Elastic Security"
        id = "02c12676-4101-44ae-be7c-d93717d04b0a"
        fingerprint = "e2e1233f5c9f24da37e1abf2c216c31505fd3f061bd0228c2c6da9036f3c863b"
        creation_date = "2022-12-22"
        last_modified = "2026-05-22"
        description = "LinPEAS detection based on the Base module"
        threat_name = "Multi.Hacktool.LinPEAS-ng"
        reference_sample = "593333df3a1e109c73e8823e3929d52a7fc79a3064eb62004f33f11daca10d0b"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $base_0 = "$(printf '\\033')" base64
        $base_1 = "Enumerate and search Privilege Escalation vectors." base64
        $base_2 = "grep -c processor /proc/cpuinfo" base64
        $base_3 = "Do you like PEASS?" base64
        $base_4 = "RED/YELLOW: 95% a PE vector" base64
        $base_5 = "\\(root\\)|\\(shadow\\)|\\(admin\\)|\\(video\\)|\\(adm\\)|\\(wheel\\)|\\(auth\\)" base64
        $base_6 = "peass{SUIDVB1_HERE}" base64
        $base_7 = "file|free|main|more|read|split|write" base64
        $base_8 = "cap_sys_admin:mount|python" base64
        $base_9 = "timeout 1 su $(whoami) -c whoami" base64
    condition:
        5 of them
}

// ---- Multi_Hacktool_Nps.yar ----
rule Multi_Hacktool_Nps_c6eb4a27 {
    meta:
        author = "Elastic Security"
        id = "c6eb4a27-c481-41b4-914d-a27d10672d30"
        fingerprint = "1386e4cef0f347b38a4614311d585b0b83cb9526b19215392aee893e594950de"
        creation_date = "2024-01-24"
        last_modified = "2024-01-29"
        threat_name = "Multi.Hacktool.Nps"
        reference = "https://www.elastic.co/security-labs/unmasking-financial-services-intrusion-ref0657"
        reference_sample = "4714e8ad9c625070ca0a151ffc98d87d8e5da7c8ef42037ca5f43baede6cfac1"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str_info0 = "Reconnecting..."
        $str_info1 = "Loading configuration file %s successfully"
        $str_info2 = "successful start-up of local socks5 monitoring, port"
        $str_info3 = "successful start-up of local tcp monitoring, port"
        $str_info4 = "start local file system, local path %s, strip prefix %s ,remote port %"
        $str_info5 = "start local file system, local path %s, strip prefix %s ,remote port %s"
    condition:
        all of them
}

rule Multi_Hacktool_Nps_f76f257d {
    meta:
        author = "Elastic Security"
        id = "f76f257d-0286-4b4d-9f73-2add23cfd07e"
        fingerprint = "4aaa270129ce0c8fdd40aae2ebc4f6595aec91cbfea9e0188542e9c3f38eedee"
        creation_date = "2024-01-24"
        last_modified = "2024-01-29"
        threat_name = "Multi.Hacktool.Nps"
        reference = "https://www.elastic.co/security-labs/unmasking-financial-services-intrusion-ref0657"
        reference_sample = "80721b20a8667536a33fca50236f5c8e0c0d07aa7805b980e40818ab92cd9f4a"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $string_decrypt_add = { 0F B6 BC 34 ?? ?? ?? ?? 44 0F B6 84 34 ?? ?? ?? ?? 44 01 C7 40 88 BC 34 ?? ?? ?? ?? 48 FF C6 }
        $string_decrypt_xor = { 0F B6 54 ?? ?? 0F B6 74 ?? ?? 31 D6 40 88 74 ?? ?? 48 FF C0 }
        $string_decrypt_sub = { 0F B6 94 04 ?? ?? ?? ?? 0F B6 B4 04 ?? ?? ?? ?? 29 D6 40 88 B4 04 ?? ?? ?? ?? 48 FF C0 }
        $NewJsonDb_str0 = { 63 6C 69 65 6E 74 73 2E 6A 73 6F 6E }
        $NewJsonDb_str1 = { 68 6F 73 74 73 2E 6A 73 6F 6E }
    condition:
        all of them
}

// ---- Multi_Hacktool_Rakshasa.yar ----
rule Multi_Hacktool_Rakshasa_d5d3ef21 {
    meta:
        author = "Elastic Security"
        id = "d5d3ef21-e004-4cb4-8f9f-541e831c8e08"
        fingerprint = "bd25f85a419679d2278e2e3951531950296785ac888bc69b513bab0a9936eacf"
        creation_date = "2024-01-24"
        last_modified = "2024-01-29"
        threat_name = "Multi.Hacktool.Rakshasa"
        reference = "https://www.elastic.co/security-labs/unmasking-financial-services-intrusion-ref0657"
        reference_sample = "ccfa30a40445d5237aaee1e015ecfcd9bdbe7665a6dc2736b28e5ebf07ec4597"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = { 35 B8 00 00 00 48 89 74 24 38 48 89 5C 24 40 48 89 4C 24 48 48 89 54 }
        $a2 = "rakshasa/server.init.4.func2" ascii fullword
        $a3 = "type..eq.rakshasa/server.Conn" ascii fullword
        $a4 = "rakshasa_lite/aes.Str2bytes" ascii fullword
        $a5 = "rakshasa_lite/server.doShellcode" ascii fullword
    condition:
        2 of them
}

// ---- Multi_Hacktool_Stowaway.yar ----
rule Multi_Hacktool_Stowaway_89f1d452 {
    meta:
        author = "Elastic Security"
        id = "89f1d452-f40b-47da-ba75-10c90d67c13b"
        fingerprint = "313e22009ad758c0dd0977c274eb165511591e3d99a8e2dd4be00622668981da"
        creation_date = "2024-06-28"
        last_modified = "2024-07-26"
        threat_name = "Multi.Hacktool.Stowaway"
        reference_sample = "c073d3be469c8eea0f007bb37c722bad30e06dc994d3a59773838ed8be154c95"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "Stowaway/share.ActivePreAuth" ascii fullword
        $a2 = "Stowaway/agent/handler" ascii fullword
        $a3 = "Origin: http://stowaway:22" ascii fullword
        $a4 = "Stowaway/admin.NewAdmin" ascii fullword
        $a5 = "Stowaway/global/global.go" ascii fullword
        $a6 = "Stowaway/crypto.AESDecrypt" ascii fullword
        $a7 = "Stowaway/utils.CheckIfIP4" ascii fullword
        $a8 = "Exit Stowaway"
        $a9 = "Stowaway/protocol.ConstructMessage" ascii fullword
    condition:
        3 of them
}

// ---- Multi_Hacktool_SuperShell.yar ----
rule Multi_Hacktool_SuperShell_f7486598 {
    meta:
        author = "Elastic Security"
        id = "f7486598-0b60-4b40-932e-6abfba279b76"
        fingerprint = "116f89157bfe0d80ddcb8f55984169fa611a51a3d562ef719b13ef2ddd50c432"
        creation_date = "2024-09-12"
        last_modified = "2024-09-30"
        threat_name = "Multi.Hacktool.SuperShell"
        reference_sample = "18556a794f5d47f93d375e257fa94b9fb1088f3021cf79cc955eb4c1813a95da"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "NHAS/reverse_ssh/internal/terminal"
        $b1 = "foreground|fingerprint|proxy|process_name"
        $b2 = "Failed to kill shell"
        $b3 = "Missing listening address"
    condition:
        $a and 1 of ($b*)
}

// ---- Multi_Ransomware_0Apt.yar ----
rule Multi_Ransomware_0Apt_b4df54d2 {
    meta:
        author = "Elastic Security"
        id = "b4df54d2-0cab-430f-bf70-cf7e5a8de5ef"
        fingerprint = "a84e26e81f96e1bae603fba2c50982c7254383b4b1c09364272d76039ec2041f"
        creation_date = "2026-06-02"
        last_modified = "2026-06-26"
        threat_name = "Multi.Ransomware.0Apt"
        reference_sample = "660f0eab11b7fc3db7da4b5c103afba236d77cb9641b158f22852578632125bc"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a0 = "Wallpaper set ho raha hai" fullword
        $a1 = ".0aptREADME0apt.txt"
        $a2 = "public_key.pemcompany.txt"
        $a3 = "::: 0APT LOCKER :::" fullword
        $a4 = "0APT-KEY" fullword
        $a5 = "README0apt.txt"
        $a6 = "encrypted by \"0apt\" group"
    condition:
        all of them
}

// ---- Multi_Ransomware_Akira.yar ----
rule Multi_Ransomware_Akira_21842eb3 {
    meta:
        author = "Elastic Security"
        id = "21842eb3-9ccc-4dec-9536-37791ef79714"
        fingerprint = "62f1a985bb718fa27c56d2f23d4f36a5b90b35626f0ef5def83441d27122a503"
        creation_date = "2024-11-21"
        last_modified = "2024-11-22"
        threat_name = "Multi.Ransomware.Akira"
        reference_sample = "3298d203c2acb68c474e5fdad8379181890b4403d6491c523c13730129be3f75"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "Well, for now let's keep all the tears and resentment to ourselves"
    condition:
        all of them
}

// ---- Multi_Ransomware_BlackCat.yar ----
rule Multi_Ransomware_BlackCat_aaf312c3 {
    meta:
        author = "Elastic Security"
        id = "aaf312c3-47b4-4dab-b7fc-8a2ac9883772"
        fingerprint = "577c7f24a7ecf89a542e9a63a1744a129c96c32e8dccfbf779dd9fc6c0194930"
        creation_date = "2022-02-02"
        last_modified = "2023-09-20"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "0c6f444c6940a3688ffc6f8b9d5774c032e3551ebbccb64e4280ae7fc1fac479"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $chacha20_enc = { EF D9 F3 0F 7F 14 3B F3 0F 7F 5C 3B 10 83 C7 20 39 F8 75 D0 8B }
        $crc32_imp = { F3 0F 6F 02 66 0F 6F D1 66 0F 3A 44 CD 11 83 C0 F0 83 C2 10 66 0F 3A 44 D4 00 83 F8 0F 66 0F EF C8 66 0F EF CA }
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_00e525d7 {
    meta:
        author = "Elastic Security"
        id = "00e525d7-a8a6-475f-89ad-607c452aea1e"
        fingerprint = "631e30b8b51a5c0a0e91e8c09968663192569005b8bffff9f0474749788e9d57"
        creation_date = "2022-02-02"
        last_modified = "2022-08-16"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "0c6f444c6940a3688ffc6f8b9d5774c032e3551ebbccb64e4280ae7fc1fac479"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "ata\",\"boot\",\"config.msi\",\"google\",\"perflogs\",\"appdata\",\"windows.old\"],\"exclude_file_names\":[\"desktop.ini\",\"aut"
        $a2 = "locker::core::windows::processvssadmin.exe delete shadows /all /quietshadow_copy::remove_all=" ascii fullword
        $a3 = "\\\\.\\pipe\\__rust_anonymous_pipe1__." ascii fullword
        $a4 = "--bypass-p-p--bypass-path-path --no-prop-servers \\\\" ascii fullword
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_c4b043e6 {
    meta:
        author = "Elastic Security"
        id = "c4b043e6-ff5f-4492-94e3-fd688d690738"
        fingerprint = "3e89858e90632ad5f4831427bd630252113b735c51f7a1aa1eab8ba6e4c16f18"
        creation_date = "2022-09-12"
        last_modified = "2022-09-29"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "45b8678f74d29c87e2d06410245ab6c2762b76190594cafc9543fb9db90f3d4f"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = { 28 4C 8B 60 08 4C 8B 68 10 0F 10 40 28 0F 29 44 24 10 0F 10 }
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_70171625 {
    meta:
        author = "Elastic Security"
        id = "70171625-c29b-47c1-b572-2e6dc846a907"
        fingerprint = "f3f70f92fe9c044f4565fca519cb04a3a54536985c2614077ef92c3193fff9c1"
        creation_date = "2023-01-05"
        last_modified = "2023-09-20"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "0c6f444c6940a3688ffc6f8b9d5774c032e3551ebbccb64e4280ae7fc1fac479"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str0 = "}RECOVER-${EXTENSION}-FILES.txt"
        $str1 = "?access-key=${ACCESS_KEY}"
        $str2 = "${NOTE_FILE_NAME}"
        $str3 = "enable_network_discovery"
        $str4 = "enable_set_wallpaper"
        $str5 = "enable_esxi_vm_kill"
        $str6 = "strict_include_paths"
        $str7 = "exclude_file_path_wildcard"
        $str8 = "${ACCESS_KEY}${EXTENSION}"
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_e066d802 {
    meta:
        author = "Elastic Security"
        id = "e066d802-b803-4e35-9b53-ae1823662483"
        fingerprint = "05037af3395b682d1831443757376064c873815ac4b6d1c09116715570f51f5d"
        creation_date = "2023-07-27"
        last_modified = "2023-09-20"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "00360830bf5886288f23784b8df82804bf6f22258e410740db481df8a7701525"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "esxcli vm process kill --type=force --world-id=Killing"
        $a2 = "vim-cmd vmsvc/snapshot.removeall $i"
        $a3 = "File already has encrypted extension"
    condition:
        2 of them
}

rule Multi_Ransomware_BlackCat_0ffb0a37 {
    meta:
        author = "Elastic Security"
        id = "0ffb0a37-e4c3-45be-bd4d-7033e88635aa"
        fingerprint = "319b956ddd57bea22cbee7e521649969c5b1f42ee4af49ad6f25847fb8ee9559"
        creation_date = "2023-07-29"
        last_modified = "2024-06-12"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "57136b118a0d6d3c71e522ea53e3305dae58b51f06c29cd01c0c28fa0fa34287"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = { C8 C8 00 00 00 89 20 00 00 45 01 00 00 32 22 08 0A 20 64 85 }
        $a2 = { 67 69 74 68 75 62 2E 63 6F 6D 2D 31 65 63 63 36 32 39 39 64 62 39 65 63 38 32 33 2F 73 69 6D 70 6C 65 6C 6F 67 2D }
    condition:
        all of them
}

// ---- Multi_Ransomware_Gentlemen.yar ----
rule Multi_Ransomware_Gentlemen_ce5b1d49 {
    meta:
        author = "Elastic Security"
        id = "ce5b1d49-ca2f-4b3b-af34-a3fde469abe4"
        fingerprint = "77b306bab0a3554fad5cd78f6405564ccde37a52a0cb56fed4d9f1da364b1047"
        creation_date = "2026-06-08"
        last_modified = "2026-06-26"
        threat_name = "Multi.Ransomware.Gentlemen"
        reference_sample = "dce2e5cc00eff2493f8ced546dc51f9d5ef78c5ee56805906ec642dfa77a1c70"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "README-GENTLEMEN.txt"
        $b = "gentlemen.bmp"
        $c = "gentlemen_system"
        $d = "TOX CONTACT - RECOVER YOUR FILES" fullword
        $e = "third-party recovery tools are useless" fullword
        $f = "Gentlemen, your network has been encrypted" fullword
        $g = "[+] Lateral movement finished" fullword
        $h = "[+] GPO deployment complete" fullword
        $i = "Error: --fast, --superfast, and --ultrafast cannot be used together."
    condition:
        4 of them
}

// ---- Multi_Ransomware_Luna.yar ----
rule Multi_Ransomware_Luna_8614d3d7 {
    meta:
        author = "Elastic Security"
        id = "8614d3d7-7fd2-4cf9-aa97-48a8d9333f38"
        fingerprint = "90c97ecfce451e1373af0d7538cf12991cc844d05c99ee18570e176143ccd899"
        creation_date = "2022-08-02"
        last_modified = "2022-08-16"
        threat_name = "Multi.Ransomware.Luna"
        reference = "https://www.elastic.co/security-labs/luna-ransomware-attack-pattern"
        reference_sample = "1cbbf108f44c8f4babde546d26425ca5340dccf878d306b90eb0fbec2f83ab51"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str_extensions = ".ini.exe.dll.lnk"
        $str_ransomnote_bs64 = "W1dIQVQgSEFQUEVORUQ/XQ0KDQpBbGwgeW91ciBmaWxlcyB3ZXJlIG1vdmVkIHRvIHNlY3VyZSBzdG9yYWdlLg0KTm9ib"
        $str_path = "/home/username/"
        $str_error1 = "Error while writing encrypted data to:"
        $str_error2 = "Error while writing public key to:"
        $str_error3 = "Error while renaming file:"
        $chunk_calculation0 = { 48 8D ?? 00 00 48 F4 48 B9 8B 3D 10 B6 9A 5A B4 36 48 F7 E1 48 }
        $chunk_calculation1 = { 48 C1 EA 12 48 89 D0 48 C1 E0 05 48 29 D0 48 29 D0 48 3D C4 EA 00 00 }
    condition:
        5 of ($str_*) or all of ($chunk_*)
}

// ---- Multi_Ransomware_Qilin.yar ----
rule Multi_Ransomware_Qilin_53ee48e0 {
    meta:
        author = "Elastic Security"
        id = "53ee48e0-9de4-45a2-b4ab-05bd17cd9476"
        fingerprint = "d5bb9c5357d6f25d56df3209defbe6526bd1d0d9823f2d20d490e745198b4822"
        creation_date = "2026-06-05"
        last_modified = "2026-06-26"
        threat_name = "Multi.Ransomware.Qilin"
        reference_sample = "bd1cf7823cabbac2ea7b45f2d7c9dfcd6b9a24714b6d40377bdef82b9c88021b"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $seq_1 = { 89 85 68 FE FF FF 89 B5 70 FD FF FF C7 85 6C FE FF FF 30 E1 42 00 }
        $seq_2 = { C6 40 08 27 89 41 08 C7 41 04 03 00 00 00 C7 01 00 00 00 00 }
        $seq_3 = { 89 5D 88 C7 45 B0 90 44 5A 00 C7 45 8C 02 00 00 00 }
        $str_1 = "[DEBUG|VOLUME] Found logical volume:" fullword
        $str_2 = "no-sandbox" fullword
        $str_3 = "README-RECOVER-.txt" fullword
        $str_4 = "-- Qilin " fullword
    condition:
        2 of them
}

// ---- Multi_Ransomware_RansomHub.yar ----
rule Multi_Ransomware_RansomHub_4a8a07cd {
    meta:
        author = "Elastic Security"
        id = "4a8a07cd-700b-4514-a808-334c0a7641de"
        fingerprint = "c66b9c6889d0c4598bf2baa99a5d137a2e2ffd06dcd2141b08a6c1eec772a87c"
        creation_date = "2024-09-05"
        last_modified = "2024-09-30"
        threat_name = "Multi.Ransomware.RansomHub"
        reference_sample = "bfbbba7d18be1aa2e85390fa69a761302756ee9348b7343af6f42f3b5d0a939c"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "white_files" ascii fullword
        $a2 = "note_file_name" ascii fullword
        $a3 = "note_short_text" ascii fullword
        $a4 = "set_wallpaper" ascii fullword
        $a5 = "local_disks" ascii fullword
        $a6 = "running_one" ascii fullword
        $a7 = "net_spread" ascii fullword
        $a8 = "kill_processes" ascii fullword
    condition:
        5 of them
}

// ---- Multi_Trojan_Coreimpact.yar ----
rule Multi_Trojan_Coreimpact_37703dc3 {
    meta:
        author = "Elastic Security"
        id = "37703dc3-9485-4026-a8b7-82e753993757"
        fingerprint = "5a4d7af7d0fecc05f87ba51f976d78e77622f8afb1eafc175444f45839490109"
        creation_date = "2022-08-10"
        last_modified = "2022-09-29"
        threat_name = "Multi.Trojan.Coreimpact"
        reference_sample = "2d954908da9f63cd3942c0df2e8bb5fe861ac5a336ddef2bd0a977cebe030ad7"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str1 = "Uh, oh, exit() failed" fullword
        $str2 = "agent_recv" fullword
        $str3 = "needroot" fullword
        $str4 = "time is running backwards, corrected" fullword
        $str5 = "junk pointer, too low to make sense" fullword
    condition:
        3 of them
}

// ---- Multi_Trojan_EmpirGo.yar ----
rule Multi_Trojan_EmpirGo_38a23b2c {
    meta:
        author = "Elastic Security"
        id = "38a23b2c-574b-40a4-9cc7-b25e64ca83fa"
        fingerprint = "856d1a8ac1c5d117656a1ad1f47cba379fa1612252d6e3900fed8103474db8a3"
        creation_date = "2025-04-23"
        last_modified = "2025-05-27"
        threat_name = "Multi.Trojan.EmpirGo"
        reference_sample = "c233aa4d7a672f08f6375f68e1f153d11e8e73df5adf72325a2e1a272f0428fc"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "EmpirGo/agent.(*MainAgent)."
        $b1 = "MissedCheckins"
        $b2 = "ReadDataDirBaseRels"
        $b3 = "getRandomSleepTime"
    condition:
        $a1 or all of ($b*)
}

// ---- Multi_Trojan_FinalDraft.yar ----
rule Multi_Trojan_FinalDraft_81975d51 {
    meta:
        author = "Elastic Security"
        id = "81975d51-96e9-4a49-97ee-56e2c60e9702"
        fingerprint = "a2d5e2f472499ad6c5ff052eded73fa182bb20cecb9c3921f37bd779a2a77c9b"
        creation_date = "2024-12-03"
        last_modified = "2025-02-04"
        threat_name = "Multi.Trojan.FinalDraft"
        reference_sample = "fa2a6dbc83fe55df848dfcaaf3163f8aaefe0c9727b3ead1da6b9fa78b598f2b"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "[-] socket() failed!"
        $a2 = "MailFolders/drafts/messages?$filter=Subject"
        $a3 = "{\"subject\":\"p_%llu\",\"body\":"
        $a4 = "COutLookTransChannel"
        $a5 = "CTransChannel"
        $a6 = "Chrome/40.0.2214.85 Safari/537.36"
    condition:
        3 of them
}

rule Multi_Trojan_FinalDraft_69deb8cd {
    meta:
        author = "Elastic Security"
        id = "69deb8cd-050b-4b92-86c2-ea54f836ce72"
        fingerprint = "3e48740092918896132e801ae4d850ef804f9dd6c8db96b80065224566c17819"
        creation_date = "2024-12-03"
        last_modified = "2025-02-04"
        threat_name = "Multi.Trojan.FinalDraft"
        reference_sample = "fa2a6dbc83fe55df848dfcaaf3163f8aaefe0c9727b3ead1da6b9fa78b598f2b"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = { 33 FF C7 44 24 20 3A 00 77 00 4C 8B F1 C7 44 24 24 74 00 66 00 48 83 C8 FF C7 44 24 28 62 00 62 00 C7 44 24 2C 71 00 00 00 48 8D 4C 24 20 }
        $a2 = { 48 81 EC B0 00 00 00 48 8B 05 00 5B 05 00 48 33 C4 48 89 84 24 A0 00 00 00 0F 57 C0 0F 11 44 24 48 4C 8B C2 48 8D 54 24 48 E8 00 0B 00 00 90 48 83 7C 24 50 00 0F 84 31 01 00 00 48 8B 7C 24 48 }
        $a3 = { 48 8D 7C 24 48 C6 43 40 00 48 C7 43 48 00 00 00 00 48 C7 43 50 00 00 00 00 48 89 43 68 48 8B ?? ?? ?? ?? 00 48 C7 43 58 00 00 00 00 C7 43 60 00 00 00 00 48 C7 43 70 00 00 00 00 C6 43 78 00 48 8D B0 FD 00 00 00 }
        $a4 = { 48 83 EC 58 B9 0D 00 00 00 BE 1E 00 00 00 64 48 8B 04 25 28 00 00 00 48 89 44 24 48 31 C0 48 8D 7C 24 14 48 C7 44 24 08 00 00 00 00 F3 AB 48 8D 7C 24 14 E8 }
    condition:
        any of them
}

// ---- Multi_Trojan_Goffloader.yar ----
rule Multi_Trojan_Goffloader_d1f4201e {
    meta:
        author = "Elastic Security"
        id = "d1f4201e-74ce-4f72-a661-47c2fb993623"
        fingerprint = "f8457fca4d8307639839199ef5fd01c8a5ad425dd341b3a5f8e5a6a9fad16329"
        creation_date = "2025-04-23"
        last_modified = "2025-05-27"
        threat_name = "Multi.Trojan.Goffloader"
        reference_sample = "c233aa4d7a672f08f6375f68e1f153d11e8e73df5adf72325a2e1a272f0428fc"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "praetorian-inc/goffloader/src/memory.ReadUIntFromPtr"
    condition:
        all of them
}

// ---- Multi_Trojan_Gosar.yar ----
rule Multi_Trojan_Gosar_31dba745 {
    meta:
        author = "Elastic Security"
        id = "31dba745-8079-4161-9299-84a4c33b95c8"
        fingerprint = "87e44b3050eb33edb24ad8aa8923ed91124f2e92e4eae42e94decefc49ccbf4c"
        creation_date = "2024-11-05"
        last_modified = "2024-12-04"
        threat_name = "Multi.Trojan.Gosar"
        reference_sample = "4caf4b280e61745ce53f96f48a74dea3b69df299c3b9de78ba4731b83c76c334"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "GetRecoverAccounts"
        $a2 = "GetIsFirstScreen"
        $a3 = "DoWebcamStop"
        $a4 = "DoAskElevate"
        $a5 = "vibrant/proto/pb"
        $a6 = "vibrant/network/sender"
        $a7 = "vibrant/pkg/helpers"
    condition:
        3 of them
}

rule Multi_Trojan_Gosar_670efa04 {
    meta:
        author = "Elastic Security"
        id = "670efa04-a5c9-40b4-bcdf-453af8162a6f"
        fingerprint = "7a0f61bb77e16baceafd60d3041002bb551f64c567ef9f495362718716c53c6a"
        creation_date = "2025-09-02"
        last_modified = "2025-09-19"
        threat_name = "Multi.Trojan.Gosar"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $byte_sequence_1 = { C6 44 24 3B 00 C6 44 24 3B 01 48 89 C1 48 89 DF 48 8D 74 24 3B 41 B8 01 00 00 00 4D 89 C1 48 8B 84 24 D8 00 00 00 48 8B 9C 24 E0 00 00 00 }
        $a_clip_board0 = "<b>[CLIPBOARD_START]</b><xmp>"
        $a_clip_board1 = "</b>]</p><br>[Applications]"
        $a_clip_board2 = "replace clipboard content failed"
    condition:
        $byte_sequence_1 or all of ($a_clip_board*)
}

// ---- Multi_Trojan_Merlin.yar ----
rule Multi_Trojan_Merlin_32643f4c {
    meta:
        author = "Elastic Security"
        id = "32643f4c-ee47-4ed2-9807-7b85d3f4e095"
        fingerprint = "bce277ef43c67be52b67c4495652e99d4707975c79cb30b54283db56545278ae"
        creation_date = "2024-03-01"
        last_modified = "2024-05-23"
        threat_name = "Multi.Trojan.Merlin"
        reference_sample = "84b988c4656677bc021e23df2a81258212d9ceba13be204867ac1d9d706404e2"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "json:\"killdate,omitempty\""
        $a2 = "json:\"maxretry,omitempty\""
        $a3 = "json:\"waittime,omitempty\""
        $a4 = "json:\"payload,omitempty\""
        $a5 = "json:\"skew,omitempty\""
        $a6 = "json:\"command\""
        $a7 = "json:\"pid,omitempty\""
        $b1 = "/merlin-agent/commands"
        $b2 = "/merlin/pkg/jobs"
        $b3 = "github.com/Ne0nd0g/merlin"
    condition:
        all of ($a*) or all of ($b*)
}

// ---- Multi_Trojan_Mythic.yar ----
rule Multi_Trojan_Mythic_4beb7e17 {
    meta:
        author = "Elastic Security"
        id = "4beb7e17-34c2-4f5c-a668-e54512175f53"
        fingerprint = "0b25c5b069cec31e9af31b7822ea19b813fe1882dfaa584661ff14414ae41df5"
        creation_date = "2023-08-01"
        last_modified = "2023-09-20"
        threat_name = "Multi.Trojan.Mythic"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "task_id"
        $a2 = "post_response"
        $a3 = "c2_profile"
        $a4 = "get_tasking"
        $a5 = "tasking_size"
        $a6 = "get_delegate_tasks"
        $a7 = "total_chunks"
        $a8 = "is_screenshot"
        $a9 = "file_browser"
        $a10 = "is_file"
        $a11 = "access_time"
    condition:
        7 of them
}

rule Multi_Trojan_Mythic_e0ea7ef9 {
    meta:
        author = "Elastic Security"
        id = "e0ea7ef9-452c-404c-95ba-4057ec40ef4b"
        fingerprint = "57afe989db139314a7505a2ccc01367cdd13132318dc19b57d4b79f65bfe982c"
        creation_date = "2024-05-23"
        last_modified = "2024-06-12"
        threat_name = "Multi.Trojan.Mythic"
        reference_sample = "e091d63c8e8b0a32a3d25cffdf02419fdbec714f31e4061bafd80b1971831c5f"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $profile1 = "src/profiles/mod.rs"
        $profile2 = "src/profiles/http.rs"
        $rs_ssh1 = "src/ssh/spawn.rs"
        $rs_ssh2 = "src/ssh/agent.rs"
        $rs_ssh3 = "src/ssh/cat.rs"
        $rs_ssh4 = "src/ssh/upload.rs"
        $rs_ssh5 = "src/ssh/exec.rs"
        $rs_ssh6 = "src/ssh/download.rs"
        $rs_ssh7 = "src/ssh/rm.rs"
        $rs_ssh8 = "src/ssh/ls.rs"
        $rs_misc1 = "src/utils/linux.rs"
        $rs_misc2 = "src/portscan.rs"
        $rs_misc3 = "src/payloadvars.rs"
        $rs_misc4 = "src/getprivs.rs"
    condition:
        all of ($profile*) and 8 of ($rs*)
}

rule Multi_Trojan_Mythic_528324b4 {
    meta:
        author = "Elastic Security"
        id = "528324b4-822d-4e48-b4ab-f5b234348773"
        fingerprint = "5188aa792c02acf7a6346f395389390ae187cb08083bfca27283a4f4dd4d7206"
        creation_date = "2024-05-23"
        last_modified = "2024-06-12"
        threat_name = "Multi.Trojan.Mythic"
        reference_sample = "2cd883eab722a5eacbca7fa82e0eebb5f6c30cffa955abcb1ab8cf169af97202"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $import1 = "Autofac"
        $import2 = "Obfuscar"
        $import3 = "Agent.Profiles.Http"
        $import4 = "Agent.Managers.Linux"
        $import5 = "Agent.Managers.Reflection"
        $athena1 = "Athena.Commands.dll"
        $athena2 = "Athena.Handler.Linux.dll"
        $athena3 = "Athena.dll"
        $athena4 = "Athena.Profiles.HTTP.dll"
    condition:
        (2 of ($import*)) or (2 of ($athena*))
}

// ---- Multi_Trojan_Sliver.yar ----
rule Multi_Trojan_Sliver_42298c4a {
    meta:
        author = "Elastic Security"
        id = "42298c4a-fcea-4c5a-b213-32db00e4eb5a"
        fingerprint = "0734b090ea10abedef4d9ed48d45c834dd5cf8e424886a5be98e484f69c5e12a"
        creation_date = "2021-10-20"
        last_modified = "2022-01-14"
        threat_name = "Multi.Trojan.Sliver"
        reference_sample = "3b45aae401ac64c055982b5f3782a3c4c892bdb9f9a5531657d50c27497c8007"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = ").RequestResend"
        $a2 = ").GetPrivInfo"
        $a3 = ").GetReconnectIntervalSeconds"
        $a4 = ").GetPivotID"
        $a5 = "name=PrivInfo"
        $a6 = "name=ReconnectIntervalSeconds"
        $a7 = "name=PivotID"
    condition:
        2 of them
}

rule Multi_Trojan_Sliver_3bde542d {
    meta:
        author = "Elastic Security"
        id = "3bde542d-df52-4f05-84ff-de67e90592a9"
        fingerprint = "e52e39644274e3077769da4d04488963c85a0b691dc9973ad12d51eb34ba388b"
        creation_date = "2022-08-31"
        last_modified = "2022-09-29"
        threat_name = "Multi.Trojan.Sliver"
        reference_sample = "05461e1c2a2e581a7c30e14d04bd3d09670e281f9f7c60f4169e9614d22ce1b3"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "B/Z-github.com/bishopfox/sliver/protobuf/sliverpbb" ascii fullword
        $b1 = "InvokeSpawnDllReq" ascii fullword
        $b2 = "NetstatReq" ascii fullword
        $b3 = "HTTPSessionInit" ascii fullword
        $b4 = "ScreenshotReq" ascii fullword
        $b5 = "RegistryReadReq" ascii fullword
    condition:
        1 of ($a*) or all of ($b*)
}

rule Multi_Trojan_Sliver_3d6b7cd3 {
    meta:
        author = "Elastic Security"
        id = "3d6b7cd3-f702-470c-819c-8750ec040083"
        fingerprint = "46d5388bd1fe767a4852c9e35420985d5011368dac6545fd57fbb256de9a94e9"
        creation_date = "2022-12-01"
        last_modified = "2023-09-20"
        threat_name = "Multi.Trojan.Sliver"
        reference_sample = "9846124cfd124eed466465d187eeacb4d405c558dd84ba8e575d8a7b3290403e"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $session_start_x86_1 = { 89 4C 24 ?? 89 44 24 ?? 8D 4C 24 ?? 89 4C 24 ?? C6 44 24 ?? ?? 89 04 24 E8 ?? ?? ?? ?? 8B 44 24 ?? 89 44 24 ?? C7 44 24 ?? ?? ?? ?? ?? }
        $session_start_x86_2 = { FF 05 ?? ?? ?? ?? 8D 05 ?? ?? ?? ?? 89 04 24 C7 44 24 ?? ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 44 24 ?? 8B 4C 24 ?? 85 C9 74 ?? B8 ?? ?? ?? ?? }
        $session_start_x86_3 = { E8 ?? ?? ?? ?? 8B 44 24 ?? 85 C0 74 ?? FF 05 ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 04 24 39 05 ?? ?? ?? ?? 7E ?? C6 44 24 ?? ?? 8B 54 24 ?? 8B 02 FF D0 83 C4 ?? }
        $session_start_x64_1 = { 44 0F 11 7C 24 ?? 48 8D 0D ?? ?? ?? ?? 48 89 4C 24 ?? 48 89 44 24 ?? 48 8D 4C 24 ?? 48 89 4C 24 ?? C6 44 24 ?? ?? 0F 1F 00 E8 ?? ?? ?? ?? 48 89 44 24 ?? 48 C7 44 24 ?? ?? ?? ?? ?? EB ?? E8 ?? ?? ?? ?? E8 ?? ?? ?? ?? }
        $session_start_x64_2 = { E8 ?? ?? ?? ?? 48 85 C0 74 ?? 48 FF 05 ?? ?? ?? ?? 48 8D 05 ?? ?? ?? ?? BB ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 85 DB B9 ?? ?? ?? ?? 48 0F 45 C1 48 39 05 ?? ?? ?? ?? 7E ?? C6 44 24 ?? ?? 48 8B 54 24 ?? 48 8B 02 FF D0 }
        $session_start_x64_3 = { 48 89 6C 24 ?? 48 8D 6C 24 ?? 49 C7 C5 ?? ?? ?? ?? 4C 89 6C 24 ?? C6 44 24 ?? ?? 48 8D 05 ?? ?? ?? ?? 31 DB E8 ?? ?? ?? ?? 44 0F 11 7C 24 ?? 48 8D 0D ?? ?? ?? ?? 48 89 4C 24 ?? 48 89 44 24 ?? 48 8D 4C 24 ?? 48 89 4C 24 ?? C6 44 24 ?? ?? 0F 1F 00 }
        $register_x64_1 = { 48 81 EC ?? ?? ?? ?? 48 89 AC 24 ?? ?? ?? ?? 48 8D AC 24 ?? ?? ?? ?? 90 E8 ?? ?? ?? ?? 48 89 44 24 ?? 48 89 5C 24 ?? 48 89 4C 24 ?? 0F 1F 44 00 ?? E8 ?? ?? ?? ?? 48 8B 4C 24 ?? 48 85 C9 48 8B 4C 24 ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 89 4C 24 ?? 48 8B 54 24 ?? BE ?? ?? ?? ?? 48 0F 45 D6 48 89 54 24 ?? }
        $register_x64_2 = { 48 8D 1D ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 8D 84 24 ?? ?? ?? ?? }
        $register_x64_3 = { E8 ?? ?? ?? ?? 48 89 84 24 ?? ?? ?? ?? 48 89 5C 24 ?? 48 89 4C 24 ?? 66 90 E8 ?? ?? ?? ?? 48 8B 4C 24 ?? 48 85 C9 48 8B 8C 24 ?? ?? ?? ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 8B 54 24 ?? BE ?? ?? ?? ?? 48 0F 45 D6 48 85 DB 74 ?? 48 8D BC 24 ?? ?? ?? ?? 48 8D 7F ?? 0F 1F 00 48 89 6C 24 ?? 48 8D 6C 24 ?? }
        $register_x64_4 = { 48 89 84 24 ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 89 8C 24 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B 8C 24 ?? ?? ?? ?? 48 85 C9 48 8B 8C 24 ?? ?? ?? ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 89 8C 24 ?? ?? ?? ?? 48 8B B4 24 ?? ?? ?? ?? BF ?? ?? ?? ?? 48 0F 45 F7 48 89 B4 24 ?? ?? ?? ?? }
        $register_x64_5 = { 48 89 84 24 ?? ?? ?? ?? 48 89 5C 24 ?? 48 89 4C 24 ?? E8 ?? ?? ?? ?? 48 8B 4C 24 ?? 48 85 C9 48 8B 8C 24 ?? ?? ?? ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 89 8C 24 ?? ?? ?? ?? 48 8B 54 24 ?? BE ?? ?? ?? ?? 48 0F 45 D6 48 89 54 24 ?? }
        $register_x64_6 = { E8 ?? ?? ?? ?? 48 8B 6D ?? 48 8B 94 24 ?? ?? ?? ?? 48 89 94 24 ?? ?? ?? ?? 48 8B 94 24 ?? ?? ?? ?? 48 89 94 24 ?? ?? ?? ?? 48 8B 94 24 ?? ?? ?? ?? 48 89 94 24 ?? ?? ?? ?? 48 8B 54 24 ?? 48 89 94 24 ?? ?? ?? ?? 48 89 84 24 ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 8D 84 24 ?? ?? ?? ?? }
        $register_x64_7 = { E8 ?? ?? ?? ?? C7 40 ?? ?? ?? ?? ?? 48 8B 4C 24 ?? 48 89 48 ?? 48 8B 4C 24 ?? 48 89 48 ?? 83 3D ?? ?? ?? ?? ?? 75 ?? }
        $register_x64_8 = { 48 8D 7F ?? 0F 1F 00 48 89 6C 24 ?? 48 8D 6C 24 ?? E8 ?? ?? ?? ?? 48 8B 6D ?? 4C 8D 15 ?? ?? ?? ?? 4C 89 94 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 4C 89 94 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 4C 89 94 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 8D 84 24 ?? ?? ?? ?? }
        $register_x86_1 = { E8 ?? ?? ?? ?? 8B 44 24 ?? 8B 0C 24 8B 54 24 ?? 85 C0 74 ?? 31 C9 31 D2 89 54 24 ?? 89 4C 24 ?? E8 ?? ?? ?? ?? 8B 04 24 8B 4C 24 ?? 85 C9 74 ?? 8D 7C 24 ?? }
        $register_x86_2 = { 8D 0D ?? ?? ?? ?? 89 4C 24 ?? C7 44 24 ?? ?? ?? ?? ?? 89 4C 24 ?? C7 44 24 ?? ?? ?? ?? ?? 89 4C 24 ?? C7 44 24 ?? ?? ?? ?? ?? 8D 44 24 ?? }
        $register_x86_3 = { C7 40 ?? ?? ?? ?? ?? 8D 0D ?? ?? ?? ?? 89 48 ?? 8B 4C 24 ?? 89 48 ?? 8B 4C 24 ?? 89 48 ?? 8B 0D ?? ?? ?? ?? 85 C9 75 ?? }
        $register_x86_4 = { E8 ?? ?? ?? ?? 8B 44 24 ?? 8B 0C 24 8B 54 24 ?? 85 C0 74 ?? 31 C9 31 D2 89 54 24 ?? 89 ?? 24 }
        $register_x86_5 = { 8B 04 24 89 84 24 ?? ?? ?? ?? 8B 4C 24 ?? 89 4C 24 ?? E8 ?? ?? ?? ?? 8B 04 24 8B 4C 24 ?? 8B 54 24 ?? 85 D2 74 ?? 31 C0 31 C9 89 4C 24 ?? 89 84 24 ?? ?? ?? ?? 8D 15 ?? ?? ?? ?? 89 14 24 E8 ?? ?? ?? ?? }
    condition:
        1 of ($session_start_*) and 1 of ($register_*)
}

// ---- Multi_Trojan_SparkRat.yar ----
rule Multi_Trojan_SparkRat_9a21e541 {
    meta:
        author = "Elastic Security"
        id = "9a21e541-886c-4d7f-8602-832862121730"
        fingerprint = "2691da3a037b651d0f7f6d7be767c34845c3b9a642f4a2fb1c54f391f08089b6"
        creation_date = "2023-11-13"
        last_modified = "2024-06-12"
        threat_name = "Multi.Trojan.SparkRat"
        reference_sample = "23efecc03506a9428175546a4b7d40c8a943c252110e83dec132c6a5db8c4dd6"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "Spark/client/service/file" ascii wide
        $a2 = "Spark/client/service/desktop" ascii wide
        $a3 = "Spark/utils.Encrypt" ascii wide
    condition:
        all of them
}
