/*
 * multi/cryptominer.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/multi/cryptominer.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     1   Upstream files: 1
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Multi_Cryptominer_Xmrig.yar ----
rule Multi_Cryptominer_Xmrig_f9516741 {
    meta:
        author = "Elastic Security"
        id = "f9516741-aac1-4c67-ad63-3d222814864e"
        fingerprint = "14eef95b5a008e644c2fe2d600c1a883d018c1ab085f4496a3e2211329362d31"
        creation_date = "2025-02-21"
        last_modified = "2025-03-07"
        threat_name = "Multi.Cryptominer.Xmrig"
        reference_sample = "104f839b5da7bd77804ca5ec252d78dccb52800a2ef4fd1179db6deb764af42f"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str_1 = "no valid configuration found, try https://xmrig.com/wizard"
        $str_2 = "xmrig-"
        $str_3 = "XMRig "
        $str_4 = "--donate-level=N"
        $str_5 = "--coin=COIN"
        $str_6 = "--algo=ALGO"
        $str_7 = "hwloc topology successfully exported to \"%s\"\n"
    condition:
        6 of them
}
