/*
 * multi/ransomware.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/multi/ransomware.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     12   Upstream files: 7
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Multi_Ransomware_0Apt.yar ----
rule Multi_Ransomware_0Apt_b4df54d2 {
    meta:
        author = "Elastic Security"
        id = "b4df54d2-0cab-430f-bf70-cf7e5a8de5ef"
        fingerprint = "a84e26e81f96e1bae603fba2c50982c7254383b4b1c09364272d76039ec2041f"
        creation_date = "2026-06-02"
        last_modified = "2026-06-26"
        threat_name = "Multi.Ransomware.0Apt"
        reference_sample = "660f0eab11b7fc3db7da4b5c103afba236d77cb9641b158f22852578632125bc"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a0 = "Wallpaper set ho raha hai" fullword
        $a1 = ".0aptREADME0apt.txt"
        $a2 = "public_key.pemcompany.txt"
        $a3 = "::: 0APT LOCKER :::" fullword
        $a4 = "0APT-KEY" fullword
        $a5 = "README0apt.txt"
        $a6 = "encrypted by \"0apt\" group"
    condition:
        all of them
}

// ---- Multi_Ransomware_Akira.yar ----
rule Multi_Ransomware_Akira_21842eb3 {
    meta:
        author = "Elastic Security"
        id = "21842eb3-9ccc-4dec-9536-37791ef79714"
        fingerprint = "62f1a985bb718fa27c56d2f23d4f36a5b90b35626f0ef5def83441d27122a503"
        creation_date = "2024-11-21"
        last_modified = "2024-11-22"
        threat_name = "Multi.Ransomware.Akira"
        reference_sample = "3298d203c2acb68c474e5fdad8379181890b4403d6491c523c13730129be3f75"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "Well, for now let's keep all the tears and resentment to ourselves"
    condition:
        all of them
}

// ---- Multi_Ransomware_BlackCat.yar ----
rule Multi_Ransomware_BlackCat_aaf312c3 {
    meta:
        author = "Elastic Security"
        id = "aaf312c3-47b4-4dab-b7fc-8a2ac9883772"
        fingerprint = "577c7f24a7ecf89a542e9a63a1744a129c96c32e8dccfbf779dd9fc6c0194930"
        creation_date = "2022-02-02"
        last_modified = "2023-09-20"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "0c6f444c6940a3688ffc6f8b9d5774c032e3551ebbccb64e4280ae7fc1fac479"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $chacha20_enc = { EF D9 F3 0F 7F 14 3B F3 0F 7F 5C 3B 10 83 C7 20 39 F8 75 D0 8B }
        $crc32_imp = { F3 0F 6F 02 66 0F 6F D1 66 0F 3A 44 CD 11 83 C0 F0 83 C2 10 66 0F 3A 44 D4 00 83 F8 0F 66 0F EF C8 66 0F EF CA }
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_00e525d7 {
    meta:
        author = "Elastic Security"
        id = "00e525d7-a8a6-475f-89ad-607c452aea1e"
        fingerprint = "631e30b8b51a5c0a0e91e8c09968663192569005b8bffff9f0474749788e9d57"
        creation_date = "2022-02-02"
        last_modified = "2022-08-16"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "0c6f444c6940a3688ffc6f8b9d5774c032e3551ebbccb64e4280ae7fc1fac479"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "ata\",\"boot\",\"config.msi\",\"google\",\"perflogs\",\"appdata\",\"windows.old\"],\"exclude_file_names\":[\"desktop.ini\",\"aut"
        $a2 = "locker::core::windows::processvssadmin.exe delete shadows /all /quietshadow_copy::remove_all=" ascii fullword
        $a3 = "\\\\.\\pipe\\__rust_anonymous_pipe1__." ascii fullword
        $a4 = "--bypass-p-p--bypass-path-path --no-prop-servers \\\\" ascii fullword
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_c4b043e6 {
    meta:
        author = "Elastic Security"
        id = "c4b043e6-ff5f-4492-94e3-fd688d690738"
        fingerprint = "3e89858e90632ad5f4831427bd630252113b735c51f7a1aa1eab8ba6e4c16f18"
        creation_date = "2022-09-12"
        last_modified = "2022-09-29"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "45b8678f74d29c87e2d06410245ab6c2762b76190594cafc9543fb9db90f3d4f"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = { 28 4C 8B 60 08 4C 8B 68 10 0F 10 40 28 0F 29 44 24 10 0F 10 }
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_70171625 {
    meta:
        author = "Elastic Security"
        id = "70171625-c29b-47c1-b572-2e6dc846a907"
        fingerprint = "f3f70f92fe9c044f4565fca519cb04a3a54536985c2614077ef92c3193fff9c1"
        creation_date = "2023-01-05"
        last_modified = "2023-09-20"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "0c6f444c6940a3688ffc6f8b9d5774c032e3551ebbccb64e4280ae7fc1fac479"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str0 = "}RECOVER-${EXTENSION}-FILES.txt"
        $str1 = "?access-key=${ACCESS_KEY}"
        $str2 = "${NOTE_FILE_NAME}"
        $str3 = "enable_network_discovery"
        $str4 = "enable_set_wallpaper"
        $str5 = "enable_esxi_vm_kill"
        $str6 = "strict_include_paths"
        $str7 = "exclude_file_path_wildcard"
        $str8 = "${ACCESS_KEY}${EXTENSION}"
    condition:
        all of them
}

rule Multi_Ransomware_BlackCat_e066d802 {
    meta:
        author = "Elastic Security"
        id = "e066d802-b803-4e35-9b53-ae1823662483"
        fingerprint = "05037af3395b682d1831443757376064c873815ac4b6d1c09116715570f51f5d"
        creation_date = "2023-07-27"
        last_modified = "2023-09-20"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "00360830bf5886288f23784b8df82804bf6f22258e410740db481df8a7701525"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "esxcli vm process kill --type=force --world-id=Killing"
        $a2 = "vim-cmd vmsvc/snapshot.removeall $i"
        $a3 = "File already has encrypted extension"
    condition:
        2 of them
}

rule Multi_Ransomware_BlackCat_0ffb0a37 {
    meta:
        author = "Elastic Security"
        id = "0ffb0a37-e4c3-45be-bd4d-7033e88635aa"
        fingerprint = "319b956ddd57bea22cbee7e521649969c5b1f42ee4af49ad6f25847fb8ee9559"
        creation_date = "2023-07-29"
        last_modified = "2024-06-12"
        threat_name = "Multi.Ransomware.BlackCat"
        reference_sample = "57136b118a0d6d3c71e522ea53e3305dae58b51f06c29cd01c0c28fa0fa34287"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = { C8 C8 00 00 00 89 20 00 00 45 01 00 00 32 22 08 0A 20 64 85 }
        $a2 = { 67 69 74 68 75 62 2E 63 6F 6D 2D 31 65 63 63 36 32 39 39 64 62 39 65 63 38 32 33 2F 73 69 6D 70 6C 65 6C 6F 67 2D }
    condition:
        all of them
}

// ---- Multi_Ransomware_Gentlemen.yar ----
rule Multi_Ransomware_Gentlemen_ce5b1d49 {
    meta:
        author = "Elastic Security"
        id = "ce5b1d49-ca2f-4b3b-af34-a3fde469abe4"
        fingerprint = "77b306bab0a3554fad5cd78f6405564ccde37a52a0cb56fed4d9f1da364b1047"
        creation_date = "2026-06-08"
        last_modified = "2026-06-26"
        threat_name = "Multi.Ransomware.Gentlemen"
        reference_sample = "dce2e5cc00eff2493f8ced546dc51f9d5ef78c5ee56805906ec642dfa77a1c70"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "README-GENTLEMEN.txt"
        $b = "gentlemen.bmp"
        $c = "gentlemen_system"
        $d = "TOX CONTACT - RECOVER YOUR FILES" fullword
        $e = "third-party recovery tools are useless" fullword
        $f = "Gentlemen, your network has been encrypted" fullword
        $g = "[+] Lateral movement finished" fullword
        $h = "[+] GPO deployment complete" fullword
        $i = "Error: --fast, --superfast, and --ultrafast cannot be used together."
    condition:
        4 of them
}

// ---- Multi_Ransomware_Luna.yar ----
rule Multi_Ransomware_Luna_8614d3d7 {
    meta:
        author = "Elastic Security"
        id = "8614d3d7-7fd2-4cf9-aa97-48a8d9333f38"
        fingerprint = "90c97ecfce451e1373af0d7538cf12991cc844d05c99ee18570e176143ccd899"
        creation_date = "2022-08-02"
        last_modified = "2022-08-16"
        threat_name = "Multi.Ransomware.Luna"
        reference = "https://www.elastic.co/security-labs/luna-ransomware-attack-pattern"
        reference_sample = "1cbbf108f44c8f4babde546d26425ca5340dccf878d306b90eb0fbec2f83ab51"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str_extensions = ".ini.exe.dll.lnk"
        $str_ransomnote_bs64 = "W1dIQVQgSEFQUEVORUQ/XQ0KDQpBbGwgeW91ciBmaWxlcyB3ZXJlIG1vdmVkIHRvIHNlY3VyZSBzdG9yYWdlLg0KTm9ib"
        $str_path = "/home/username/"
        $str_error1 = "Error while writing encrypted data to:"
        $str_error2 = "Error while writing public key to:"
        $str_error3 = "Error while renaming file:"
        $chunk_calculation0 = { 48 8D ?? 00 00 48 F4 48 B9 8B 3D 10 B6 9A 5A B4 36 48 F7 E1 48 }
        $chunk_calculation1 = { 48 C1 EA 12 48 89 D0 48 C1 E0 05 48 29 D0 48 29 D0 48 3D C4 EA 00 00 }
    condition:
        5 of ($str_*) or all of ($chunk_*)
}

// ---- Multi_Ransomware_Qilin.yar ----
rule Multi_Ransomware_Qilin_53ee48e0 {
    meta:
        author = "Elastic Security"
        id = "53ee48e0-9de4-45a2-b4ab-05bd17cd9476"
        fingerprint = "d5bb9c5357d6f25d56df3209defbe6526bd1d0d9823f2d20d490e745198b4822"
        creation_date = "2026-06-05"
        last_modified = "2026-06-26"
        threat_name = "Multi.Ransomware.Qilin"
        reference_sample = "bd1cf7823cabbac2ea7b45f2d7c9dfcd6b9a24714b6d40377bdef82b9c88021b"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $seq_1 = { 89 85 68 FE FF FF 89 B5 70 FD FF FF C7 85 6C FE FF FF 30 E1 42 00 }
        $seq_2 = { C6 40 08 27 89 41 08 C7 41 04 03 00 00 00 C7 01 00 00 00 00 }
        $seq_3 = { 89 5D 88 C7 45 B0 90 44 5A 00 C7 45 8C 02 00 00 00 }
        $str_1 = "[DEBUG|VOLUME] Found logical volume:" fullword
        $str_2 = "no-sandbox" fullword
        $str_3 = "README-RECOVER-.txt" fullword
        $str_4 = "-- Qilin " fullword
    condition:
        2 of them
}

// ---- Multi_Ransomware_RansomHub.yar ----
rule Multi_Ransomware_RansomHub_4a8a07cd {
    meta:
        author = "Elastic Security"
        id = "4a8a07cd-700b-4514-a808-334c0a7641de"
        fingerprint = "c66b9c6889d0c4598bf2baa99a5d137a2e2ffd06dcd2141b08a6c1eec772a87c"
        creation_date = "2024-09-05"
        last_modified = "2024-09-30"
        threat_name = "Multi.Ransomware.RansomHub"
        reference_sample = "bfbbba7d18be1aa2e85390fa69a761302756ee9348b7343af6f42f3b5d0a939c"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "white_files" ascii fullword
        $a2 = "note_file_name" ascii fullword
        $a3 = "note_short_text" ascii fullword
        $a4 = "set_wallpaper" ascii fullword
        $a5 = "local_disks" ascii fullword
        $a6 = "running_one" ascii fullword
        $a7 = "net_spread" ascii fullword
        $a8 = "kill_processes" ascii fullword
    condition:
        5 of them
}
