/*
 * multi/trojan.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/multi/trojan.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     15   Upstream files: 9
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Multi_Trojan_Coreimpact.yar ----
rule Multi_Trojan_Coreimpact_37703dc3 {
    meta:
        author = "Elastic Security"
        id = "37703dc3-9485-4026-a8b7-82e753993757"
        fingerprint = "5a4d7af7d0fecc05f87ba51f976d78e77622f8afb1eafc175444f45839490109"
        creation_date = "2022-08-10"
        last_modified = "2022-09-29"
        threat_name = "Multi.Trojan.Coreimpact"
        reference_sample = "2d954908da9f63cd3942c0df2e8bb5fe861ac5a336ddef2bd0a977cebe030ad7"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $str1 = "Uh, oh, exit() failed" fullword
        $str2 = "agent_recv" fullword
        $str3 = "needroot" fullword
        $str4 = "time is running backwards, corrected" fullword
        $str5 = "junk pointer, too low to make sense" fullword
    condition:
        3 of them
}

// ---- Multi_Trojan_EmpirGo.yar ----
rule Multi_Trojan_EmpirGo_38a23b2c {
    meta:
        author = "Elastic Security"
        id = "38a23b2c-574b-40a4-9cc7-b25e64ca83fa"
        fingerprint = "856d1a8ac1c5d117656a1ad1f47cba379fa1612252d6e3900fed8103474db8a3"
        creation_date = "2025-04-23"
        last_modified = "2025-05-27"
        threat_name = "Multi.Trojan.EmpirGo"
        reference_sample = "c233aa4d7a672f08f6375f68e1f153d11e8e73df5adf72325a2e1a272f0428fc"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "EmpirGo/agent.(*MainAgent)."
        $b1 = "MissedCheckins"
        $b2 = "ReadDataDirBaseRels"
        $b3 = "getRandomSleepTime"
    condition:
        $a1 or all of ($b*)
}

// ---- Multi_Trojan_FinalDraft.yar ----
rule Multi_Trojan_FinalDraft_81975d51 {
    meta:
        author = "Elastic Security"
        id = "81975d51-96e9-4a49-97ee-56e2c60e9702"
        fingerprint = "a2d5e2f472499ad6c5ff052eded73fa182bb20cecb9c3921f37bd779a2a77c9b"
        creation_date = "2024-12-03"
        last_modified = "2025-02-04"
        threat_name = "Multi.Trojan.FinalDraft"
        reference_sample = "fa2a6dbc83fe55df848dfcaaf3163f8aaefe0c9727b3ead1da6b9fa78b598f2b"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "[-] socket() failed!"
        $a2 = "MailFolders/drafts/messages?$filter=Subject"
        $a3 = "{\"subject\":\"p_%llu\",\"body\":"
        $a4 = "COutLookTransChannel"
        $a5 = "CTransChannel"
        $a6 = "Chrome/40.0.2214.85 Safari/537.36"
    condition:
        3 of them
}

rule Multi_Trojan_FinalDraft_69deb8cd {
    meta:
        author = "Elastic Security"
        id = "69deb8cd-050b-4b92-86c2-ea54f836ce72"
        fingerprint = "3e48740092918896132e801ae4d850ef804f9dd6c8db96b80065224566c17819"
        creation_date = "2024-12-03"
        last_modified = "2025-02-04"
        threat_name = "Multi.Trojan.FinalDraft"
        reference_sample = "fa2a6dbc83fe55df848dfcaaf3163f8aaefe0c9727b3ead1da6b9fa78b598f2b"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = { 33 FF C7 44 24 20 3A 00 77 00 4C 8B F1 C7 44 24 24 74 00 66 00 48 83 C8 FF C7 44 24 28 62 00 62 00 C7 44 24 2C 71 00 00 00 48 8D 4C 24 20 }
        $a2 = { 48 81 EC B0 00 00 00 48 8B 05 00 5B 05 00 48 33 C4 48 89 84 24 A0 00 00 00 0F 57 C0 0F 11 44 24 48 4C 8B C2 48 8D 54 24 48 E8 00 0B 00 00 90 48 83 7C 24 50 00 0F 84 31 01 00 00 48 8B 7C 24 48 }
        $a3 = { 48 8D 7C 24 48 C6 43 40 00 48 C7 43 48 00 00 00 00 48 C7 43 50 00 00 00 00 48 89 43 68 48 8B ?? ?? ?? ?? 00 48 C7 43 58 00 00 00 00 C7 43 60 00 00 00 00 48 C7 43 70 00 00 00 00 C6 43 78 00 48 8D B0 FD 00 00 00 }
        $a4 = { 48 83 EC 58 B9 0D 00 00 00 BE 1E 00 00 00 64 48 8B 04 25 28 00 00 00 48 89 44 24 48 31 C0 48 8D 7C 24 14 48 C7 44 24 08 00 00 00 00 F3 AB 48 8D 7C 24 14 E8 }
    condition:
        any of them
}

// ---- Multi_Trojan_Goffloader.yar ----
rule Multi_Trojan_Goffloader_d1f4201e {
    meta:
        author = "Elastic Security"
        id = "d1f4201e-74ce-4f72-a661-47c2fb993623"
        fingerprint = "f8457fca4d8307639839199ef5fd01c8a5ad425dd341b3a5f8e5a6a9fad16329"
        creation_date = "2025-04-23"
        last_modified = "2025-05-27"
        threat_name = "Multi.Trojan.Goffloader"
        reference_sample = "c233aa4d7a672f08f6375f68e1f153d11e8e73df5adf72325a2e1a272f0428fc"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a = "praetorian-inc/goffloader/src/memory.ReadUIntFromPtr"
    condition:
        all of them
}

// ---- Multi_Trojan_Gosar.yar ----
rule Multi_Trojan_Gosar_31dba745 {
    meta:
        author = "Elastic Security"
        id = "31dba745-8079-4161-9299-84a4c33b95c8"
        fingerprint = "87e44b3050eb33edb24ad8aa8923ed91124f2e92e4eae42e94decefc49ccbf4c"
        creation_date = "2024-11-05"
        last_modified = "2024-12-04"
        threat_name = "Multi.Trojan.Gosar"
        reference_sample = "4caf4b280e61745ce53f96f48a74dea3b69df299c3b9de78ba4731b83c76c334"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "GetRecoverAccounts"
        $a2 = "GetIsFirstScreen"
        $a3 = "DoWebcamStop"
        $a4 = "DoAskElevate"
        $a5 = "vibrant/proto/pb"
        $a6 = "vibrant/network/sender"
        $a7 = "vibrant/pkg/helpers"
    condition:
        3 of them
}

rule Multi_Trojan_Gosar_670efa04 {
    meta:
        author = "Elastic Security"
        id = "670efa04-a5c9-40b4-bcdf-453af8162a6f"
        fingerprint = "7a0f61bb77e16baceafd60d3041002bb551f64c567ef9f495362718716c53c6a"
        creation_date = "2025-09-02"
        last_modified = "2025-09-19"
        threat_name = "Multi.Trojan.Gosar"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $byte_sequence_1 = { C6 44 24 3B 00 C6 44 24 3B 01 48 89 C1 48 89 DF 48 8D 74 24 3B 41 B8 01 00 00 00 4D 89 C1 48 8B 84 24 D8 00 00 00 48 8B 9C 24 E0 00 00 00 }
        $a_clip_board0 = "<b>[CLIPBOARD_START]</b><xmp>"
        $a_clip_board1 = "</b>]</p><br>[Applications]"
        $a_clip_board2 = "replace clipboard content failed"
    condition:
        $byte_sequence_1 or all of ($a_clip_board*)
}

// ---- Multi_Trojan_Merlin.yar ----
rule Multi_Trojan_Merlin_32643f4c {
    meta:
        author = "Elastic Security"
        id = "32643f4c-ee47-4ed2-9807-7b85d3f4e095"
        fingerprint = "bce277ef43c67be52b67c4495652e99d4707975c79cb30b54283db56545278ae"
        creation_date = "2024-03-01"
        last_modified = "2024-05-23"
        threat_name = "Multi.Trojan.Merlin"
        reference_sample = "84b988c4656677bc021e23df2a81258212d9ceba13be204867ac1d9d706404e2"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "json:\"killdate,omitempty\""
        $a2 = "json:\"maxretry,omitempty\""
        $a3 = "json:\"waittime,omitempty\""
        $a4 = "json:\"payload,omitempty\""
        $a5 = "json:\"skew,omitempty\""
        $a6 = "json:\"command\""
        $a7 = "json:\"pid,omitempty\""
        $b1 = "/merlin-agent/commands"
        $b2 = "/merlin/pkg/jobs"
        $b3 = "github.com/Ne0nd0g/merlin"
    condition:
        all of ($a*) or all of ($b*)
}

// ---- Multi_Trojan_Mythic.yar ----
rule Multi_Trojan_Mythic_4beb7e17 {
    meta:
        author = "Elastic Security"
        id = "4beb7e17-34c2-4f5c-a668-e54512175f53"
        fingerprint = "0b25c5b069cec31e9af31b7822ea19b813fe1882dfaa584661ff14414ae41df5"
        creation_date = "2023-08-01"
        last_modified = "2023-09-20"
        threat_name = "Multi.Trojan.Mythic"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "task_id"
        $a2 = "post_response"
        $a3 = "c2_profile"
        $a4 = "get_tasking"
        $a5 = "tasking_size"
        $a6 = "get_delegate_tasks"
        $a7 = "total_chunks"
        $a8 = "is_screenshot"
        $a9 = "file_browser"
        $a10 = "is_file"
        $a11 = "access_time"
    condition:
        7 of them
}

rule Multi_Trojan_Mythic_e0ea7ef9 {
    meta:
        author = "Elastic Security"
        id = "e0ea7ef9-452c-404c-95ba-4057ec40ef4b"
        fingerprint = "57afe989db139314a7505a2ccc01367cdd13132318dc19b57d4b79f65bfe982c"
        creation_date = "2024-05-23"
        last_modified = "2024-06-12"
        threat_name = "Multi.Trojan.Mythic"
        reference_sample = "e091d63c8e8b0a32a3d25cffdf02419fdbec714f31e4061bafd80b1971831c5f"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $profile1 = "src/profiles/mod.rs"
        $profile2 = "src/profiles/http.rs"
        $rs_ssh1 = "src/ssh/spawn.rs"
        $rs_ssh2 = "src/ssh/agent.rs"
        $rs_ssh3 = "src/ssh/cat.rs"
        $rs_ssh4 = "src/ssh/upload.rs"
        $rs_ssh5 = "src/ssh/exec.rs"
        $rs_ssh6 = "src/ssh/download.rs"
        $rs_ssh7 = "src/ssh/rm.rs"
        $rs_ssh8 = "src/ssh/ls.rs"
        $rs_misc1 = "src/utils/linux.rs"
        $rs_misc2 = "src/portscan.rs"
        $rs_misc3 = "src/payloadvars.rs"
        $rs_misc4 = "src/getprivs.rs"
    condition:
        all of ($profile*) and 8 of ($rs*)
}

rule Multi_Trojan_Mythic_528324b4 {
    meta:
        author = "Elastic Security"
        id = "528324b4-822d-4e48-b4ab-f5b234348773"
        fingerprint = "5188aa792c02acf7a6346f395389390ae187cb08083bfca27283a4f4dd4d7206"
        creation_date = "2024-05-23"
        last_modified = "2024-06-12"
        threat_name = "Multi.Trojan.Mythic"
        reference_sample = "2cd883eab722a5eacbca7fa82e0eebb5f6c30cffa955abcb1ab8cf169af97202"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $import1 = "Autofac"
        $import2 = "Obfuscar"
        $import3 = "Agent.Profiles.Http"
        $import4 = "Agent.Managers.Linux"
        $import5 = "Agent.Managers.Reflection"
        $athena1 = "Athena.Commands.dll"
        $athena2 = "Athena.Handler.Linux.dll"
        $athena3 = "Athena.dll"
        $athena4 = "Athena.Profiles.HTTP.dll"
    condition:
        (2 of ($import*)) or (2 of ($athena*))
}

// ---- Multi_Trojan_Sliver.yar ----
rule Multi_Trojan_Sliver_42298c4a {
    meta:
        author = "Elastic Security"
        id = "42298c4a-fcea-4c5a-b213-32db00e4eb5a"
        fingerprint = "0734b090ea10abedef4d9ed48d45c834dd5cf8e424886a5be98e484f69c5e12a"
        creation_date = "2021-10-20"
        last_modified = "2022-01-14"
        threat_name = "Multi.Trojan.Sliver"
        reference_sample = "3b45aae401ac64c055982b5f3782a3c4c892bdb9f9a5531657d50c27497c8007"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = ").RequestResend"
        $a2 = ").GetPrivInfo"
        $a3 = ").GetReconnectIntervalSeconds"
        $a4 = ").GetPivotID"
        $a5 = "name=PrivInfo"
        $a6 = "name=ReconnectIntervalSeconds"
        $a7 = "name=PivotID"
    condition:
        2 of them
}

rule Multi_Trojan_Sliver_3bde542d {
    meta:
        author = "Elastic Security"
        id = "3bde542d-df52-4f05-84ff-de67e90592a9"
        fingerprint = "e52e39644274e3077769da4d04488963c85a0b691dc9973ad12d51eb34ba388b"
        creation_date = "2022-08-31"
        last_modified = "2022-09-29"
        threat_name = "Multi.Trojan.Sliver"
        reference_sample = "05461e1c2a2e581a7c30e14d04bd3d09670e281f9f7c60f4169e9614d22ce1b3"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "B/Z-github.com/bishopfox/sliver/protobuf/sliverpbb" ascii fullword
        $b1 = "InvokeSpawnDllReq" ascii fullword
        $b2 = "NetstatReq" ascii fullword
        $b3 = "HTTPSessionInit" ascii fullword
        $b4 = "ScreenshotReq" ascii fullword
        $b5 = "RegistryReadReq" ascii fullword
    condition:
        1 of ($a*) or all of ($b*)
}

rule Multi_Trojan_Sliver_3d6b7cd3 {
    meta:
        author = "Elastic Security"
        id = "3d6b7cd3-f702-470c-819c-8750ec040083"
        fingerprint = "46d5388bd1fe767a4852c9e35420985d5011368dac6545fd57fbb256de9a94e9"
        creation_date = "2022-12-01"
        last_modified = "2023-09-20"
        threat_name = "Multi.Trojan.Sliver"
        reference_sample = "9846124cfd124eed466465d187eeacb4d405c558dd84ba8e575d8a7b3290403e"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $session_start_x86_1 = { 89 4C 24 ?? 89 44 24 ?? 8D 4C 24 ?? 89 4C 24 ?? C6 44 24 ?? ?? 89 04 24 E8 ?? ?? ?? ?? 8B 44 24 ?? 89 44 24 ?? C7 44 24 ?? ?? ?? ?? ?? }
        $session_start_x86_2 = { FF 05 ?? ?? ?? ?? 8D 05 ?? ?? ?? ?? 89 04 24 C7 44 24 ?? ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 44 24 ?? 8B 4C 24 ?? 85 C9 74 ?? B8 ?? ?? ?? ?? }
        $session_start_x86_3 = { E8 ?? ?? ?? ?? 8B 44 24 ?? 85 C0 74 ?? FF 05 ?? ?? ?? ?? E8 ?? ?? ?? ?? 8B 04 24 39 05 ?? ?? ?? ?? 7E ?? C6 44 24 ?? ?? 8B 54 24 ?? 8B 02 FF D0 83 C4 ?? }
        $session_start_x64_1 = { 44 0F 11 7C 24 ?? 48 8D 0D ?? ?? ?? ?? 48 89 4C 24 ?? 48 89 44 24 ?? 48 8D 4C 24 ?? 48 89 4C 24 ?? C6 44 24 ?? ?? 0F 1F 00 E8 ?? ?? ?? ?? 48 89 44 24 ?? 48 C7 44 24 ?? ?? ?? ?? ?? EB ?? E8 ?? ?? ?? ?? E8 ?? ?? ?? ?? }
        $session_start_x64_2 = { E8 ?? ?? ?? ?? 48 85 C0 74 ?? 48 FF 05 ?? ?? ?? ?? 48 8D 05 ?? ?? ?? ?? BB ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 85 DB B9 ?? ?? ?? ?? 48 0F 45 C1 48 39 05 ?? ?? ?? ?? 7E ?? C6 44 24 ?? ?? 48 8B 54 24 ?? 48 8B 02 FF D0 }
        $session_start_x64_3 = { 48 89 6C 24 ?? 48 8D 6C 24 ?? 49 C7 C5 ?? ?? ?? ?? 4C 89 6C 24 ?? C6 44 24 ?? ?? 48 8D 05 ?? ?? ?? ?? 31 DB E8 ?? ?? ?? ?? 44 0F 11 7C 24 ?? 48 8D 0D ?? ?? ?? ?? 48 89 4C 24 ?? 48 89 44 24 ?? 48 8D 4C 24 ?? 48 89 4C 24 ?? C6 44 24 ?? ?? 0F 1F 00 }
        $register_x64_1 = { 48 81 EC ?? ?? ?? ?? 48 89 AC 24 ?? ?? ?? ?? 48 8D AC 24 ?? ?? ?? ?? 90 E8 ?? ?? ?? ?? 48 89 44 24 ?? 48 89 5C 24 ?? 48 89 4C 24 ?? 0F 1F 44 00 ?? E8 ?? ?? ?? ?? 48 8B 4C 24 ?? 48 85 C9 48 8B 4C 24 ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 89 4C 24 ?? 48 8B 54 24 ?? BE ?? ?? ?? ?? 48 0F 45 D6 48 89 54 24 ?? }
        $register_x64_2 = { 48 8D 1D ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 8D 84 24 ?? ?? ?? ?? }
        $register_x64_3 = { E8 ?? ?? ?? ?? 48 89 84 24 ?? ?? ?? ?? 48 89 5C 24 ?? 48 89 4C 24 ?? 66 90 E8 ?? ?? ?? ?? 48 8B 4C 24 ?? 48 85 C9 48 8B 8C 24 ?? ?? ?? ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 8B 54 24 ?? BE ?? ?? ?? ?? 48 0F 45 D6 48 85 DB 74 ?? 48 8D BC 24 ?? ?? ?? ?? 48 8D 7F ?? 0F 1F 00 48 89 6C 24 ?? 48 8D 6C 24 ?? }
        $register_x64_4 = { 48 89 84 24 ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 89 8C 24 ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B 8C 24 ?? ?? ?? ?? 48 85 C9 48 8B 8C 24 ?? ?? ?? ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 89 8C 24 ?? ?? ?? ?? 48 8B B4 24 ?? ?? ?? ?? BF ?? ?? ?? ?? 48 0F 45 F7 48 89 B4 24 ?? ?? ?? ?? }
        $register_x64_5 = { 48 89 84 24 ?? ?? ?? ?? 48 89 5C 24 ?? 48 89 4C 24 ?? E8 ?? ?? ?? ?? 48 8B 4C 24 ?? 48 85 C9 48 8B 8C 24 ?? ?? ?? ?? BA ?? ?? ?? ?? 48 0F 45 CA 48 89 8C 24 ?? ?? ?? ?? 48 8B 54 24 ?? BE ?? ?? ?? ?? 48 0F 45 D6 48 89 54 24 ?? }
        $register_x64_6 = { E8 ?? ?? ?? ?? 48 8B 6D ?? 48 8B 94 24 ?? ?? ?? ?? 48 89 94 24 ?? ?? ?? ?? 48 8B 94 24 ?? ?? ?? ?? 48 89 94 24 ?? ?? ?? ?? 48 8B 94 24 ?? ?? ?? ?? 48 89 94 24 ?? ?? ?? ?? 48 8B 54 24 ?? 48 89 94 24 ?? ?? ?? ?? 48 89 84 24 ?? ?? ?? ?? 48 89 9C 24 ?? ?? ?? ?? 48 8D 84 24 ?? ?? ?? ?? }
        $register_x64_7 = { E8 ?? ?? ?? ?? C7 40 ?? ?? ?? ?? ?? 48 8B 4C 24 ?? 48 89 48 ?? 48 8B 4C 24 ?? 48 89 48 ?? 83 3D ?? ?? ?? ?? ?? 75 ?? }
        $register_x64_8 = { 48 8D 7F ?? 0F 1F 00 48 89 6C 24 ?? 48 8D 6C 24 ?? E8 ?? ?? ?? ?? 48 8B 6D ?? 4C 8D 15 ?? ?? ?? ?? 4C 89 94 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 4C 89 94 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 4C 89 94 24 ?? ?? ?? ?? 48 C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 48 8D 84 24 ?? ?? ?? ?? }
        $register_x86_1 = { E8 ?? ?? ?? ?? 8B 44 24 ?? 8B 0C 24 8B 54 24 ?? 85 C0 74 ?? 31 C9 31 D2 89 54 24 ?? 89 4C 24 ?? E8 ?? ?? ?? ?? 8B 04 24 8B 4C 24 ?? 85 C9 74 ?? 8D 7C 24 ?? }
        $register_x86_2 = { 8D 0D ?? ?? ?? ?? 89 4C 24 ?? C7 44 24 ?? ?? ?? ?? ?? 89 4C 24 ?? C7 44 24 ?? ?? ?? ?? ?? 89 4C 24 ?? C7 44 24 ?? ?? ?? ?? ?? 8D 44 24 ?? }
        $register_x86_3 = { C7 40 ?? ?? ?? ?? ?? 8D 0D ?? ?? ?? ?? 89 48 ?? 8B 4C 24 ?? 89 48 ?? 8B 4C 24 ?? 89 48 ?? 8B 0D ?? ?? ?? ?? 85 C9 75 ?? }
        $register_x86_4 = { E8 ?? ?? ?? ?? 8B 44 24 ?? 8B 0C 24 8B 54 24 ?? 85 C0 74 ?? 31 C9 31 D2 89 54 24 ?? 89 ?? 24 }
        $register_x86_5 = { 8B 04 24 89 84 24 ?? ?? ?? ?? 8B 4C 24 ?? 89 4C 24 ?? E8 ?? ?? ?? ?? 8B 04 24 8B 4C 24 ?? 8B 54 24 ?? 85 D2 74 ?? 31 C0 31 C9 89 4C 24 ?? 89 84 24 ?? ?? ?? ?? 8D 15 ?? ?? ?? ?? 89 14 24 E8 ?? ?? ?? ?? }
    condition:
        1 of ($session_start_*) and 1 of ($register_*)
}

// ---- Multi_Trojan_SparkRat.yar ----
rule Multi_Trojan_SparkRat_9a21e541 {
    meta:
        author = "Elastic Security"
        id = "9a21e541-886c-4d7f-8602-832862121730"
        fingerprint = "2691da3a037b651d0f7f6d7be767c34845c3b9a642f4a2fb1c54f391f08089b6"
        creation_date = "2023-11-13"
        last_modified = "2024-06-12"
        threat_name = "Multi.Trojan.SparkRat"
        reference_sample = "23efecc03506a9428175546a4b7d40c8a943c252110e83dec132c6a5db8c4dd6"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "multi"
    strings:
        $a1 = "Spark/client/service/file" ascii wide
        $a2 = "Spark/client/service/desktop" ascii wide
        $a3 = "Spark/utils.Encrypt" ascii wide
    condition:
        all of them
}
