/*
 * macos/backdoor.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/macos/backdoor.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     7   Upstream files: 5
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- MacOS_Backdoor_Applejeus.yar ----
rule MacOS_Backdoor_Applejeus_a54e423c {
    meta:
        author = "Elastic Security"
        id = "a54e423c-6467-4c80-9a2a-c868d3323d77"
        fingerprint = "413318971af37b634e5022241b8b6ab85d6cf113902acacbb750a268c1c1fc22"
        creation_date = "2026-02-26"
        last_modified = "2026-04-06"
        threat_name = "MacOS.Backdoor.Applejeus"
        reference_sample = "8e2b17417cb99e7b689f46ef1c8500a33860e28e497f495c02eece2d4c3217f8"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $a = { 81 3F 28 00 00 80 74 ?? 8B 4F 04 48 01 CF FF C2 44 39 C2 }
    condition:
        all of them
}

rule MacOS_Backdoor_Applejeus_0152671e {
    meta:
        author = "Elastic Security"
        id = "0152671e-1086-4776-a3ac-87ad6e5d5dcf"
        fingerprint = "4207620255ab5bbb3ebe27d790e282a24987505c42a1876c8092370ee564712c"
        creation_date = "2026-02-27"
        last_modified = "2026-04-06"
        threat_name = "MacOS.Backdoor.Applejeus"
        reference_sample = "5e54bccbd4d93447e79cda0558b0b308a186c2be571c739e5460a3cb6ef665c0"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $a = "--jeus" fullword
        $b = "%09d-%06d" fullword
        $c = "Reply received"
        $d = "multipart/form-data;boundary=jeus" fullword
    condition:
        all of them
}

rule MacOS_Backdoor_Applejeus_71c0acb0 {
    meta:
        author = "Elastic Security"
        id = "71c0acb0-c326-4d9d-91c6-039560a4b574"
        fingerprint = "25cc2a29480b78c196f919c735918cbb98325f200d68ddc9bfcebc13aa439a21"
        creation_date = "2026-02-27"
        last_modified = "2026-04-06"
        threat_name = "MacOS.Backdoor.Applejeus"
        reference_sample = "e352d6ea4da596abfdf51f617584611fc9321d5a6d1c22aff243aecdef8e7e55"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $a = { 89 C1 83 E1 0F 42 8A 0C 39 41 30 0C 04 48 FF C0 }
        $b = { 41 C7 07 00 00 00 00 BE 00 00 03 00 4C 89 E7 }
    condition:
        all of them
}

// ---- MacOS_Backdoor_Fakeflashlxk.yar ----
rule MacOS_Backdoor_Fakeflashlxk_06fd8071 {
    meta:
        author = "Elastic Security"
        id = "06fd8071-0370-4ae8-819a-846fa0a79b3d"
        fingerprint = "a0e6763428616b46536c6a4eb080bae0cc58ef27678616aa432eb43a3d9c77a1"
        creation_date = "2021-11-11"
        last_modified = "2022-07-22"
        threat_name = "MacOS.Backdoor.Fakeflashlxk"
        reference_sample = "107f844f19e638866d8249e6f735daf650168a48a322d39e39d5e36cfc1c8659"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $s1 = "/Users/lxk/Library/Developer/Xcode/DerivedData"
        $s2 = "Desktop/SafariFlashActivity/SafariFlashActivity/SafariFlashActivity/"
        $s3 = "/Debug/SafariFlashActivity.build/Objects-normal/x86_64/AppDelegate.o"
    condition:
        2 of them
}

// ---- MacOS_Backdoor_Kagent.yar ----
rule MacOS_Backdoor_Kagent_64ca1865 {
    meta:
        author = "Elastic Security"
        id = "64ca1865-0a99-49dc-b138-02b17ed47f60"
        fingerprint = "b8086b08a019a733bee38cebdc4e25cdae9d3c238cfe7b341d8f0cd4db204d27"
        creation_date = "2021-11-11"
        last_modified = "2022-07-22"
        threat_name = "MacOS.Backdoor.Kagent"
        reference_sample = "d599d7814adbab0f1442f5a10074e00f3a776ce183ea924abcd6154f0d068bb4"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $s1 = "save saveCaptureInfo"
        $s2 = "savephoto success screenCaptureInfo"
        $s3 = "no auto bbbbbaaend:%d path %s"
        $s4 = "../screencapture/screen_capture_thread.cpp"
        $s5 = "%s:%d, m_autoScreenCaptureQueue: %x"
        $s6 = "auto bbbbbaaend:%d path %s"
        $s7 = "auto aaaaaaaastartTime:%d path %s"
    condition:
        4 of them
}

// ---- MacOS_Backdoor_Keyboardrecord.yar ----
rule MacOS_Backdoor_Keyboardrecord_832f7bac {
    meta:
        author = "Elastic Security"
        id = "832f7bac-3896-4934-b05f-8215a41cca74"
        fingerprint = "27aa4380bda0335c672e957ba2ce6fd1f42ccf0acd2eff757e30210c3b4fb2fa"
        creation_date = "2021-11-11"
        last_modified = "2022-07-22"
        threat_name = "MacOS.Backdoor.Keyboardrecord"
        reference_sample = "570cd76bf49cf52e0cb347a68bdcf0590b2eaece134e1b1eba7e8d66261bdbe6"
        severity = 100
        arch_context = "x86"
        scan_context = "file"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $s1 = "com.ccc.keyboardrecord"
        $s2 = "com.ccc.write_queue"
        $s3 = "ps -p %s > /dev/null"
        $s4 = "useage %s path useragentpid"
        $s5 = "keyboardRecorderStartPKc"
    condition:
        3 of them
}

// ---- MacOS_Backdoor_Useragent.yar ----
rule MacOS_Backdoor_Useragent_1a02fc3a {
    meta:
        author = "Elastic Security"
        id = "1a02fc3a-a394-457b-8af5-99f7f22b0a3b"
        fingerprint = "22afa14a3dc6f8053b93bf3e971d57808a9cc19e676f9ed358ba5f1db9292ba4"
        creation_date = "2021-11-11"
        last_modified = "2022-07-22"
        threat_name = "MacOS.Backdoor.Useragent"
        reference_sample = "623f99cbe20af8b79cbfea7f485d47d3462d927153d24cac4745d7043c15619a"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $s1 = "/Library/LaunchAgents/com.UserAgent.va.plist"
        $s2 = "this is not root"
        $s3 = "rm -Rf "
        $s4 = "/start.sh"
        $s5 = ".killchecker_"
    condition:
        4 of them
}
