/*
 * macos/infostealer.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/macos/infostealer.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     12   Upstream files: 8
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- MacOS_Infostealer_MdQueryPassw.yar ----
rule MacOS_Infostealer_MdQueryPassw_6125f987 {
    meta:
        author = "Elastic Security"
        id = "6125f987-b5a4-4999-ab39-ff312a43f6d9"
        fingerprint = "744e5e82bd90dc75031c2ce8208e9b8d10f062a57666f7e7be9428321f2929cc"
        creation_date = "2023-04-11"
        last_modified = "2024-08-19"
        threat_name = "MacOS.Infostealer.MdQueryPassw"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $string1 = /kMDItemTextContent\s{1,50}==\s{1,50}\S{1,50}passw/ ascii wide nocase
        $string2 = /kMDItemDisplayName\s{1,50}==\s{1,50}\S{1,50}passw\S{1,50}/ ascii wide nocase
    condition:
        any of ($string1, $string2)
}

// ---- MacOS_Infostealer_MdQuerySecret.yar ----
rule MacOS_Infostealer_MdQuerySecret_5535ab96 {
    meta:
        author = "Elastic Security"
        id = "5535ab96-36aa-42ed-ab85-d8fd7fa6a368"
        fingerprint = "4fdad65ffdce106e837bbec747e63269f782a9b1ab2cfa9d2db204d252960ab4"
        creation_date = "2023-04-11"
        last_modified = "2024-08-19"
        threat_name = "MacOS.Infostealer.MdQuerySecret"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $string1 = /kMDItemTextContent\s{1,50}==\s{1,50}\S{1,50}secret/ ascii wide nocase
        $string2 = /kMDItemDisplayName\s{1,50}==\s{1,50}\S{1,50}secret\S{1,50}/ ascii wide nocase
    condition:
        any of ($string1, $string2)
}

// ---- MacOS_Infostealer_MdQueryTCC.yar ----
rule MacOS_Infostealer_MdQueryTCC_142313cb {
    meta:
        author = "Elastic Security"
        id = "142313cb-4726-442d-957c-5078440b8940"
        fingerprint = "280fa2c49461d0b53425768b9114696104c3ed0241ed157c22e36cdbaa334ac9"
        creation_date = "2023-04-11"
        last_modified = "2024-08-19"
        threat_name = "MacOS.Infostealer.MdQueryTCC"
        reference_sample = "d895075057e491b34b0f8c0392b44e43ade425d19eaaacea6ef8c5c9bd3487d8"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $string1 = { 6B 4D 44 49 74 65 6D 44 69 73 70 6C 61 79 4E 61 6D 65 20 ( 3D | 3D ) 20 2A 54 43 43 2E 64 62 }
    condition:
        any of them
}

// ---- MacOS_Infostealer_MdQueryToken.yar ----
rule MacOS_Infostealer_MdQueryToken_1c52d574 {
    meta:
        author = "Elastic Security"
        id = "1c52d574-4fb7-4f14-b100-291e3f296c94"
        fingerprint = "f603e5383d08050cd84949fb60ce5618c4dfff54bcb3f035290adc1c1cc0e0e1"
        creation_date = "2023-04-11"
        last_modified = "2024-08-19"
        threat_name = "MacOS.Infostealer.MdQueryToken"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $string1 = /kMDItemTextContent\s{1,50}==\s{1,50}\S{1,50}token/ ascii wide nocase
        $string2 = /kMDItemDisplayName\s{1,50}==\s{1,50}\S{1,50}token\S{1,50}/ ascii wide nocase
    condition:
        any of ($string1, $string2)
}

// ---- Macos_Infostealer_Atomic.yar ----
rule Macos_Infostealer_Atomic_94ac4578 {
    meta:
        author = "Elastic Security"
        id = "94ac4578-2514-4331-ada9-5a63cd833cc3"
        fingerprint = "b07afdfb657a5f22ef6ee23b5ee3b9b2822911fad03fe33a7fec5d2038092687"
        creation_date = "2024-03-06"
        last_modified = "2024-04-06"
        threat_name = "Macos.Infostealer.Atomic"
        reference_sample = "bafd232300548838af32b72443ed44c8ed63e840d0726c3c10e9b6d73d179165"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $s1 = { 5F 00 5F 5F 5A 34 68 6D 6D 6D 76 00 5F 5F 5A 4E 53 74 33 5F 5F 31 70 6C }
        $s2 = { 48 6F 73 74 3A 50 4F 53 54 20 2F 6A 6F 69 6E 73 79 73 74 65 6D 64 }
        $s3 = "dscl /Local/Defa/password-enterens/login.keychai/Library"
        $s4 = "fNS40Mi42NS4xMDc= HTTP/1.1"
        $s5 = "efcagfbpxyzvshakagqgrahpjgtf/Build"
    condition:
        any of them
}

// ---- Macos_Infostealer_Banshee.yar ----
rule Macos_Infostealer_Banshee_08f6de7b {
    meta:
        author = "Elastic Security"
        id = "08f6de7b-88d0-4f3b-9c80-8938d2b874a0"
        fingerprint = "4d9726035e318128db04f0ac05e14abc2c452393eb264a9dd83a2aa697fa2dea"
        creation_date = "2024-08-13"
        last_modified = "2025-08-18"
        threat_name = "Macos.Infostealer.Banshee"
        reference_sample = "11aa6eeca2547fcf807129787bec0d576de1a29b56945c5a8fb16ed8bf68f782"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $str_0 = "No debugging, VM, or Russian language detected." ascii fullword
        $str_1 = "Remote IP: " ascii fullword
        $str_2 = "Russian language detected!" ascii fullword
        $str_3 = " is empty or does not exist, skipping." ascii fullword
        $str_4 = "Data posted successfully" ascii fullword
        $binary_0 = { 8B 55 BC 0F BE 08 31 D1 88 08 48 8B 45 D8 48 83 C0 01 48 89 45 D8 E9 }
        $binary_1 = { 48 83 EC 60 48 89 7D C8 48 89 F8 48 89 45 D0 48 89 7D F8 48 89 75 F0 48 89 55 E8 C6 45 E7 00 }
    condition:
        all of ($str_*) or all of ($binary_*)
}

rule Macos_Infostealer_Banshee_5d6bfde9 {
    meta:
        author = "Elastic Security"
        id = "5d6bfde9-f5ac-4988-a8c9-f22954073a79"
        fingerprint = "70f926f87f57018d1cf2b5aac0b8e7975d0ddbe8c1aecbd58a49956e54a27b72"
        creation_date = "2024-09-13"
        last_modified = "2024-10-24"
        threat_name = "Macos.Infostealer.Banshee"
        reference_sample = "03ca50947875b4498013503cd4e26282ff764b8d7a1dc1d801d1d08595986cf8"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $binary_0 = { 89 F0 31 D2 41 F7 F6 0F B6 04 11 41 30 04 37 48 8D 46 01 48 89 C2 4C 09 F2 48 C1 EA 20 }
        $str_0 = { 64 69 74 74 6F 20 2D 63 20 2D 6B 20 25 40 20 25 40 2E 7A 69 70 20 2D 2D 6E 6F 72 73 72 63 20 2D 2D 6E 6F 65 78 74 61 74 74 72 00 }
        $str_1 = "run_controller"
        $str_2 = "initWithEncryptionKey"
        $str_3 = "killall Terminal"
    condition:
        $binary_0 and all of ($str_*)
}

rule Macos_Infostealer_Banshee_cde28dbe {
    meta:
        author = "Elastic Security"
        id = "cde28dbe-10b5-4da4-898c-412d7376e296"
        fingerprint = "ce349c617b19e2fcab1c1d316e16d414a45ed57eb3b3cab91b4c9b177f591875"
        creation_date = "2024-10-29"
        last_modified = "2025-08-18"
        threat_name = "Macos.Infostealer.Banshee"
        reference_sample = "63598afdf56de10043289a7489cccf6c71c203bc68f165f66d2a06e04b65a225"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $str_0 = "dumpKeychainPasswords" ascii fullword
        $str_1 = "compressFolder:" ascii fullword
        $str_2 = "collectWalletData" ascii fullword
        $str_3 = "getMacOSPassword" ascii fullword
        $str_4 = "collectDataFromBrowser:browserPath:" ascii fullword
        $str_5 = "Exodus/exodus.wallet/"
        $b_0 = { 64 69 73 70 6C 61 79 20 64 69 61 6C 6F 67 20 22 54 6F 20 6C 61 75 6E 63 68 20 74 68 65 20 61 70 70 6C 69 63 61 74 69 6F 6E 2C 20 79 6F 75 20 6E 65 65 64 20 74 6F 20 75 70 64 61 74 65 20 74 68 65 20 73 79 73 74 65 6D 20 73 65 74 74 69 6E 67 73 20 0A 0A 50 6C 65 61 73 65 20 65 6E 74 65 72 20 79 6F 75 72 20 70 61 73 73 77 6F 72 64 2E 22 20 77 69 74 68 20 74 69 74 6C 65 20 22 53 79 73 74 65 6D 20 50 72 65 66 65 72 65 6E 63 65 73 22 20 77 69 74 68 20 69 63 6F 6E 20 63 61 75 74 69 6F 6E 20 64 65 66 61 75 6C 74 20 61 6E 73 77 65 72 20 22 22 20 67 69 76 69 6E 67 20 75 70 20 61 66 74 65 72 20 33 30 20 77 69 74 68 20 68 69 64 64 65 6E 20 61 6E 73 77 65 72 27 }
    condition:
        all of ($str_*) or $b_0
}

rule Macos_Infostealer_Banshee_977412ed {
    meta:
        author = "Elastic Security"
        id = "977412ed-4f10-4634-94e9-074629cd2c94"
        fingerprint = "dc49e9e9392ff2b8202df6f011b4494671d8a88c7efbef171b68394709d5706b"
        creation_date = "2025-02-28"
        last_modified = "2025-08-18"
        threat_name = "Macos.Infostealer.Banshee"
        reference_sample = "082579d348d64cece46a726072ed87f4839f44b8a90d415c2383fcdd7566be9f"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $binary_0 = { 48 89 C8 48 29 D0 48 D1 E8 48 01 D0 48 C1 E8 02 48 8D 14 C5 00 00 00 00 48 29 D0 48 01 C8 41 8A 04 07 43 88 04 26 }
        $binary_1 = { 48 C7 C2 FF FF FF FF 88 0C 10 41 8A 4C 16 02 48 FF C2 84 C9 75 }
        $binary_2 = { 88 14 31 8A 54 30 02 48 FF C6 84 D2 75 }
        $arm_binary_0 = { 08 7C 40 93 09 7D D6 9B 08 01 09 CB 28 05 48 8B 08 FD 42 D3 08 0D 08 CB 08 C1 20 8B A8 6A 68 38 E8 16 00 38 18 07 00 F1 }
    condition:
        ($binary_0 and $binary_2) or ($binary_1 and $binary_2) or $arm_binary_0
}

rule Macos_Infostealer_Banshee_a49cb4b0 {
    meta:
        author = "Elastic Security"
        id = "a49cb4b0-8c14-439d-9306-db76a421344f"
        fingerprint = "46d147ebb42fd356318d380f82160ecd6ba29efd3f62b846bd945837458d54b5"
        creation_date = "2025-12-30"
        last_modified = "2026-04-06"
        threat_name = "Macos.Infostealer.Banshee"
        reference_sample = "00c68fb8bcb44581f15cb4f888b4dec8cd6d528cacb287dc1bdeeb34299b8c93"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $x64_a = { 49 89 F0 49 D3 E8 44 30 07 48 83 C2 08 48 FF C7 }
        $x64_b = { 88 14 08 8A 54 31 02 48 FF C1 48 83 F9 }
        $arm_a = { 2B 25 CB 9A 4C 01 40 39 8B 01 0B 4A 4B 15 00 38 08 21 00 91 }
        $arm_b = { 0A 69 29 38 8A 05 40 39 29 05 00 91 }
    condition:
        all of ($x64_*) or all of ($arm_*)
}

// ---- Macos_Infostealer_EncodedOsascript.yar ----
rule Macos_Infostealer_EncodedOsascript_eeb54a7e {
    meta:
        author = "Elastic Security"
        id = "eeb54a7e-ebb3-4bf9-8538-2dbad9e514b9"
        fingerprint = "db8d78a931b64c2658f9b908e73e412a173a11f37b4f6f62becfde2e1f1bc394"
        creation_date = "2024-08-19"
        last_modified = "2024-08-26"
        threat_name = "Macos.Infostealer.EncodedOsascript"
        reference_sample = "c1693ee747e31541919f84dfa89e36ca5b74074044b181656d95d7f40af34a05"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $xor_encoded_osascript = "osascript" xor(64)
        $base32_encoded_osascript = { 4E 35 5A 57 43 34 33 44 4F 4A 55 58 41 35 }
        $hex_encoded_osascript = "6f7361736372697074" ascii wide nocase
    condition:
        any of them
}

// ---- Macos_Infostealer_Wallets.yar ----
rule Macos_Infostealer_Wallets_8e469ea0 {
    meta:
        author = "Elastic Security"
        id = "8e469ea0-0c68-444b-b19a-4e1ab89f94b2"
        fingerprint = "a974450459cafbf24462fe221d6d9a5dff33c1ba6998157d3666c93869595eb0"
        creation_date = "2024-03-06"
        last_modified = "2025-01-30"
        threat_name = "Macos.Infostealer.Wallets"
        reference_sample = "0e649facc5c82f7112997c7629bd114e63acc1c8dc9ede646214243ace9b9c1d"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "macos"
    strings:
        $s1 = "ibnejdfjmmkpcnlpebklmnkoeoihofec" ascii wide
        $s2 = "fhbohimaelbohpjbbldcngcnapndodjp" ascii wide
        $s3 = "ffnbelfdoeiohenkjibnmadjiehjhajb" ascii wide
        $s4 = "jbdaocneiiinmjbjlgalhcelgbejmnid" ascii wide
        $s5 = "afbcbjpbpfadlkmhmclhkeeodmamcflc" ascii wide
        $s6 = "hnfanknocfeofbddgcijnmhnfnkdnaad" ascii wide
        $s7 = "hpglfhgfnhbgpjdenjgmdgoeiappafln" ascii wide
        $s8 = "blnieiiffboillknjnepogjhkgnoapac" ascii wide
        $s9 = "cjelfplplebdjjenllpjcblmjkfcffne" ascii wide
        $s10 = "fihkakfobkmkjojpchpfgcmhfjnmnfpi" ascii wide
        $s11 = "kncchdigobghenbbaddojjnnaogfppfj" ascii wide
        $s12 = "amkmjjmmflddogmhpjloimipbofnfjih" ascii wide
        $s13 = "nlbmnnijcnlegkjjpcfjclmcfggfefdm" ascii wide
        $s14 = "nanjmdknhkinifnkgdcggcfnhdaammmj" ascii wide
        $s15 = "nkddgncdjgjfcddamfgcmfnlhccnimig" ascii wide
        $s16 = "fnjhmkhhmkbjkkabndcnnogagogbneec" ascii wide
        $s17 = "cphhlgmgameodnhkjdmkpanlelnlohao" ascii wide
        $s18 = "nhnkbkgjikgcigadomkphalanndcapjk" ascii wide
        $s19 = "kpfopkelmapcoipemfendmdcghnegimn" ascii wide
        $s20 = "aiifbnbfobpmeekipheeijimdpnlpgpp" ascii wide
        $s21 = "dmkamcknogkgcdfhhbddcghachkejeap" ascii wide
        $s22 = "fhmfendgdocmcbmfikdcogofphimnkno" ascii wide
        $s23 = "cnmamaachppnkjgnildpdmkaakejnhae" ascii wide
        $s24 = "jojhfeoedkpkglbfimdfabpdfjaoolaf" ascii wide
        $s25 = "flpiciilemghbmfalicajoolhkkenfel" ascii wide
        $s26 = "nknhiehlklippafakaeklbeglecifhad" ascii wide
        $s27 = "hcflpincpppdclinealmandijcmnkbgn" ascii wide
        $s28 = "ookjlbkiijinhpmnjffcofjonbfbgaoc" ascii wide
        $s29 = "mnfifefkajgofkcjkemidiaecocnkjeh" ascii wide
        $s30 = "lodccjjbdhfakaekdiahmedfbieldgik" ascii wide
        $s31 = "ijmpgkjfkbfhoebgogflfebnmejmfbml" ascii wide
        $s32 = "lkcjlnjfpbikmcmbachjpdbijejflpcm" ascii wide
        $s33 = "nkbihfbeogaeaoehlefnkodbefgpgknn" ascii wide
        $s34 = "bcopgchhojmggmffilplmbdicgaihlkp" ascii wide
        $s35 = "klnaejjgbibmhlephnhpmaofohgkpgkd" ascii wide
        $s36 = "aeachknmefphepccionboohckonoeemg" ascii wide
        $s37 = "dkdedlpgdmmkkfjabffeganieamfklkm" ascii wide
        $s38 = "nlgbhdfgdhgbiamfdfmbikcdghidoadd" ascii wide
        $s39 = "onofpnbbkehpmmoabgpcpmigafmmnjhl" ascii wide
        $s40 = "cihmoadaighcejopammfbmddcmdekcje" ascii wide
        $s41 = "cgeeodpfagjceefieflmdfphplkenlfk" ascii wide
        $s42 = "pdadjkfkgcafgbceimcpbkalnfnepbnk" ascii wide
        $s43 = "acmacodkjbdgmoleebolmdjonilkdbch" ascii wide
        $s44 = "bfnaelmomeimhlpmgjnjophhpkkoljpa" ascii wide
        $s45 = "fhilaheimglignddkjgofkcbgekhenbh" ascii wide
        $s46 = "mgffkfbidihjpoaomajlbgchddlicgpn" ascii wide
        $s47 = "hmeobnfnfcmdkdcmlblgagmfpfboieaf" ascii wide
        $s48 = "lpfcbjknijpeeillifnkikgncikgfhdo" ascii wide
        $s49 = "dngmlblcodfobpdpecaadgfbcggfjfnm" ascii wide
        $s50 = "bhhhlbepdkbapadjdnnojkbgioiodbic" ascii wide
        $s51 = "jnkelfanjkeadonecabehalmbgpfodjm" ascii wide
        $s52 = "jhgnbkkipaallpehbohjmkbjofjdmeid" ascii wide
        $s53 = "jnlgamecbpmbajjfhmmmlhejkemejdma" ascii wide
        $s54 = "kkpllkodjeloidieedojogacfhpaihoh" ascii wide
        $s55 = "mcohilncbfahbmgdjkbpemcciiolgcge" ascii wide
        $s56 = "gjagmgiddbbciopjhllkdnddhcglnemk" ascii wide
        $s57 = "kmhcihpebfmpgmihbkipmjlmmioameka" ascii wide
        $s58 = "phkbamefinggmakgklpkljjmgibohnba" ascii wide
        $s59 = "lpilbniiabackdjcionkobglmddfbcjo" ascii wide
        $s60 = "cjmkndjhnagcfbpiemnkdpomccnjblmj" ascii wide
        $s61 = "aijcbedoijmgnlmjeegjaglmepbmpkpi" ascii wide
        $s62 = "efbglgofoippbgcjepnhiblaibcnclgk" ascii wide
        $s63 = "odbfpeeihdkbihmopkbjmoonfanlbfcl" ascii wide
        $s64 = "fnnegphlobjdpkhecapkijjdkgcjhkib" ascii wide
        $s65 = "aodkkagnadcbobfpggfnjeongemjbjca" ascii wide
        $s66 = "akoiaibnepcedcplijmiamnaigbepmcb" ascii wide
        $s67 = "ejbalbakoplchlghecdalmeeeajnimhm" ascii wide
        $s68 = "dfeccadlilpndjjohbjdblepmjeahlmm" ascii wide
        $s69 = "kjmoohlgokccodicjjfebfomlbljgfhk" ascii wide
        $s70 = "ajkhoeiiokighlmdnlakpjfoobnjinie" ascii wide
        $s71 = "fplfipmamcjaknpgnipjeaeeidnjooao" ascii wide
        $s72 = "niihfokdlimbddhfmngnplgfcgpmlido" ascii wide
        $s73 = "obffkkagpmohennipjokmpllocnlndac" ascii wide
        $s74 = "kfocnlddfahihoalinnfbnfmopjokmhl" ascii wide
        $s75 = "infeboajgfhgbjpjbeppbkgnabfdkdaf" ascii wide
        $s76 = "{530f7c6c-6077-4703-8f71-cb368c663e35}.xpi" ascii wide
        $s77 = "ronin-wallet@axieinfinity.com.xpi" ascii wide
        $s78 = "webextension@metamask.io.xpi" ascii wide
        $s79 = "{5799d9b6-8343-4c26-9ab6-5d2ad39884ce}.xpi" ascii wide
        $s80 = "{aa812bee-9e92-48ba-9570-5faf0cfe2578}.xpi" ascii wide
        $s81 = "{59ea5f29-6ea9-40b5-83cd-937249b001e1}.xpi" ascii wide
        $s82 = "{d8ddfc2a-97d9-4c60-8b53-5edd299b6674}.xpi" ascii wide
        $s83 = "{7c42eea1-b3e4-4be4-a56f-82a5852b12dc}.xpi" ascii wide
        $s84 = "{b3e96b5f-b5bf-8b48-846b-52f430365e80}.xpi" ascii wide
        $s85 = "{eb1fb57b-ca3d-4624-a841-728fdb28455f}.xpi" ascii wide
        $s86 = "{76596e30-ecdb-477a-91fd-c08f2018df1a}.xpi" ascii wide
        $s87 = "ejjladinnckdgjemekebdpeokbikhfci" ascii wide
        $s88 = "bgpipimickeadkjlklgciifhnalhdjhe" ascii wide
        $s89 = "epapihdplajcdnnkdeiahlgigofloibg" ascii wide
        $s90 = "aholpfdialjgjfhomihkjbmgjidlcdno" ascii wide
        $s91 = "egjidjbpglichdcondbcbdnbeeppgdph" ascii wide
        $s92 = "pnndplcbkakcplkjnolgbkdgjikjednm" ascii wide
        $s93 = "gojhcdgcpbpfigcaejpfhfegekdgiblk" ascii wide
    condition:
        6 of them
}
