/*
 * windows/backdoor.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/windows/backdoor.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     4   Upstream files: 3
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Windows_Backdoor_DragonCastling.yar ----
rule Windows_Backdoor_DragonCastling_4ecf6f9f {
    meta:
        author = "Elastic Security"
        id = "4ecf6f9f-a4c8-4962-9f16-cf7fb76467d3"
        fingerprint = "be22acb2c9c28b68d9fffe255f7d72065fb683ef2e3c4f73914f51e14ae43175"
        creation_date = "2022-11-08"
        last_modified = "2022-12-20"
        threat_name = "Windows.Backdoor.DragonCastling"
        reference_sample = "9776c7ae6ca73f87d7c838257a5bcd946372fbb77ebed42eebdfb633b13cd387"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a1 = "recv bomb" ascii fullword
        $a2 = "%s\\kbg%x.dat"
        $a3 = "\\smcache.dat" wide fullword
        $a4 = "%s\\game_%x.log"
        $a5 = "{%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X}"
        $a7 = "HOST: %ws:%ws" ascii fullword
        $a8 = "; Windows NT %d.%d" wide fullword
        $a9 = "Mozilla / 5.0 (Windows NT 6.3; WOW64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 41.0.2272.118 Safari / 537.36" ascii fullword
        $a10 = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\User Agent\\Post Platform" wide fullword
    condition:
        5 of them
}

// ---- Windows_Backdoor_Goldbackdoor.yar ----
rule Windows_Backdoor_Goldbackdoor_91902940 {
    meta:
        author = "Elastic Security"
        id = "91902940-a291-4fc6-81c5-2cde2328e8d9"
        fingerprint = "83a404a24e54bd05319d3df3a830f1ffe51d30f71ca55d63ca152d5169511df4"
        creation_date = "2022-04-29"
        last_modified = "2022-06-09"
        threat_name = "Windows.Backdoor.Goldbackdoor"
        reference_sample = "485246b411ef5ea9e903397a5490d106946a8323aaf79e6041bdf94763a0c028"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $pdf = "D:\\Development\\GOLD-BACKDOOR\\"
        $agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.3112.113 Safari/537.36"
        $str0 = "client_id"
        $str1 = "client_secret"
        $str2 = "redirect_uri"
        $str3 = "refresh_token"
        $a = { 56 57 8B 7D 08 8B F1 6A 00 6A 00 6A 00 6A 00 68 ?? ?? ?? ?? FF 15 ?? ?? ?? ?? 89 46 30 85 C0 75 ?? 33 C0 5F 5E }
        $b = { 66 8B 02 83 C2 02 66 85 C0 75 ?? 2B D1 D1 FA 75 ?? 33 C0 E9 ?? ?? ?? ?? 6A 40 8D 45 ?? 6A 00 50 E8 }
    condition:
        ($pdf and $agent) or (all of ($str*) and $a and $b)
}

rule Windows_Backdoor_Goldbackdoor_f11d57df {
    meta:
        author = "Elastic Security"
        id = "f11d57df-8dd4-481c-a557-f83ae05d53fe"
        fingerprint = "fed0317d43910d962908604812c2cd1aff6e67f7e245c82b39f2ac6dc14b6edb"
        creation_date = "2022-04-29"
        last_modified = "2022-06-09"
        threat_name = "Windows.Backdoor.Goldbackdoor"
        reference_sample = "45ece107409194f5f1ec2fbd902d041f055a914e664f8ed2aa1f90e223339039"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a = { C7 45 ?? 64 69 72 25 C7 45 ?? 5C 53 79 73 C7 45 ?? 74 65 6D 33 C7 45 ?? 32 5C 00 00 C7 45 ?? 2A 2E 65 78 C7 45 ?? 65 00 00 00 E8 ?? ?? ?? ?? FF D0 }
        $b = { B9 18 48 24 9D E8 ?? ?? ?? ?? FF D0 }
        $c = { B9 F8 92 FA 98 E8 ?? ?? ?? ?? FF D0 }
        $a1 = { 64 A1 30 00 00 00 53 55 56 }
        $b1 = { B9 76 DB 7A AA 6A 40 68 00 30 00 00 FF 75 ?? 50 E8 ?? ?? ?? ?? FF D0 }
        $c1 = { B9 91 51 13 EE 50 68 80 00 00 00 6A 04 50 50 ?? ?? ?? ?? ?? ?? ?? 6A 04 50 E8 ?? ?? ?? ?? FF D0 }
    condition:
        all of them
}

// ---- Windows_Backdoor_TeamViewer.yar ----
rule Windows_Backdoor_TeamViewer_df8e7326 {
    meta:
        author = "Elastic Security"
        id = "df8e7326-5879-48d7-8a5f-1c9a2d8b7f8d"
        fingerprint = "0f2406e98fa1383e39672bd4ec32a111363f7d33f8bc33c2bd7ea36353faab45"
        creation_date = "2022-10-29"
        last_modified = "2022-12-20"
        threat_name = "Windows.Backdoor.TeamViewer"
        reference = "https://vms.drweb.com/virus/?i=8172096"
        reference_sample = "68d9ffb6e00c2694d0d827108d0410d5a66d4f8cf839afddd17c5887b0149350"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a1 = "m%c%c%c%c%c%c.com" ascii fullword
        $a2 = "client_id=%.8x&connected=%d&server_port=%d&debug=%d&os=%d.%d.%04d&dgt=%d&dti=%d" ascii fullword
        $a3 = "\\save.dat" ascii fullword
        $a4 = "auth_ip" ascii fullword
        $a5 = "updips" ascii fullword
        $b1 = { 55 8B EC 56 E8 BF 25 00 00 50 E8 7B 5B 00 00 8B F0 59 85 F6 75 2C 8B 75 08 56 E8 A9 25 00 00 50 }
    condition:
        5 of ($a*) or 1 of ($b*)
}
