/*
 * windows/infostealer.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/windows/infostealer.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     5   Upstream files: 5
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Windows_Infostealer_EddieStealer.yar ----
rule Windows_Infostealer_EddieStealer_12a21c75 {
    meta:
        author = "Elastic Security"
        id = "12a21c75-554e-47df-b9c2-2523296af8f3"
        fingerprint = "e624a0005d0cb4b577fae9450f91e0a5d26e0c2d72a305c6f7737474551e5f92"
        creation_date = "2025-04-16"
        last_modified = "2026-01-06"
        threat_name = "Windows.Infostealer.EddieStealer"
        reference_sample = "47409e09afa05fcc9c9eff2c08baca3084d923c8d82159005dbae2029e1959d0"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a = { 48 8B 8C 24 ?? ?? ?? ?? C7 84 24 ?? ?? ?? ?? ?? ?? ?? ?? 8B 94 24 ?? ?? ?? ?? E8 }
        $b = { 48 ?? AA AA 00 00 AA AA AA AA 4? 89 ?? 04 4? 89 ?? 0C 66 [1-2] AA AA }
        $c = { 4? 89 [1-2] 0F 28 05 ?? ?? ?? ?? 0F 11 ?? 08 0F 11 ?? 18 0F 11 ?? 23 0F 57 C0 }
        $d = { 4? 8B 14 ?? 48 33 14 08 48 89 94 0C ?? ?? ?? ?? 48 83 C1 08 EB }
        $e = { 48 83 EC 38 48 8B 09 48 8B 01 48 83 21 00 48 85 C0 0F 84 ?? ?? ?? ?? 48 8B 30 48 ?? ?? ?? ?? ?? ?? 48 8D 54 24 28 48 89 02 48 8B 0A C7 ?? ?? ?? ?? ?? 48 8D 7C 24 28 8B 17 E8 }
    condition:
        4 of them
}

// ---- Windows_Infostealer_Generic.yar ----
rule Windows_Infostealer_Generic_acde9261 {
    meta:
        author = "Elastic Security"
        id = "acde9261-9dcb-4797-a5ae-cc470928622c"
        fingerprint = "b56f87041429209b63bb28513c3cee10e4e088dad43dd2fd2bd90cda0fe91d75"
        creation_date = "2024-10-21"
        last_modified = "2024-10-24"
        description = "Observed in Stealc/Vidar samples"
        threat_name = "Windows.Infostealer.Generic"
        reference_sample = "b46239c47a835757bba49078728f693b7273b0e3755e2968deac4aa92e90364d"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $str1 = "ChromeFuckNewCookies" ascii fullword
        $str2 = "/c timeout /t 10 & del /f /q \"" ascii fullword
        $str3 = "56574883EC2889D74889CEE8AAAAFFFF85FF74084889F1E8AAAAAAAA4889F04883C4285F5EC3CCCCCCCCCCCCCCCCCCCC56574883ECAA"
        $seq1 = { 81 FA 6B 03 EE 4C 74 ?? 81 FA 77 03 EE 4C 74 ?? 81 FA 80 68 55 FB 74 ?? 81 FA 92 68 55 FB }
    condition:
        2 of them
}

// ---- Windows_Infostealer_NovaBlight.yar ----
rule Windows_Infostealer_NovaBlight_b80703b9 {
    meta:
        author = "Elastic Security"
        id = "b80703b9-9a23-43b4-b28b-c6da29e4f414"
        fingerprint = "492a380d919e191b07e748b09fa89dd9c5addef5635bd5b623363dd748df1cc5"
        creation_date = "2025-07-18"
        last_modified = "2025-07-28"
        threat_name = "Windows.Infostealer.NovaBlight"
        reference_sample = "d806d6b5811965e745fd444b8e57f2648780cc23db9aa2c1675bc9d18530ab73"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a1 = "C:\\Users\\Administrateur\\Desktop\\Nova\\"
        $a2 = "[+] Recording..." fullword
        $a3 = "[+] Capture start" fullword
    condition:
        all of them
}

// ---- Windows_Infostealer_PhemedroneStealer.yar ----
rule Windows_Infostealer_PhemedroneStealer_bed8ea8a {
    meta:
        author = "Elastic Security"
        id = "bed8ea8a-f2a3-4a51-ae57-4986da4d21aa"
        fingerprint = "29702a2dc8b20c230ffef00dfff725133b707e35523e075ff85484a20da3c760"
        creation_date = "2024-03-21"
        last_modified = "2024-05-08"
        threat_name = "Windows.Infostealer.PhemedroneStealer"
        reference_sample = "38279fdad25c7972be9426cadb5ad5e3ee7e9761b0a41ed617945cb9a3713702"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a1 = "<KillDebuggers>b_"
        $a2 = "<Key3Database>b_"
        $a3 = "<IsVM>b_"
        $a4 = "<ParseDatWallets>b_"
        $a5 = "<ParseExtensions>b_"
        $a6 = "<ParseDiscordTokens>b_"
        $b1 = "Phemedrone.Senders"
        $b2 = "Phemedrone.Protections"
        $b3 = "Phemedrone.Extensions"
        $b4 = "Phemedrone.Cryptography"
        $b5 = "Phemedrone-Report.zip"
        $b6 = "Phemedrone Stealer Report"
    condition:
        all of ($a*) or all of ($b*)
}

// ---- Windows_Infostealer_Strela.yar ----
rule Windows_Infostealer_Strela_0dc3e4a1 {
    meta:
        author = "Elastic Security"
        id = "0dc3e4a1-13ac-4461-aac9-896f9e30d84b"
        fingerprint = "76ba0b9c5e892afc335d101dfc30355b6d704f2d723a81ddbae1cf2026ea85a4"
        creation_date = "2024-03-25"
        last_modified = "2024-09-30"
        threat_name = "Windows.Infostealer.Strela"
        reference_sample = "e6991b12e86629b38e178fef129dfda1d454391ffbb236703f8c026d6d55b9a1"
        severity = 100
        arch_context = "x86"
        scan_context = "memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $s1 = "strela" fullword
        $s2 = "/server.php" fullword
        $s3 = "/out.php" fullword
        $s4 = "%s%s\\key4.db" fullword
        $s5 = "%s%s\\logins.json" fullword
        $s6 = "%s,%s,%s\n" fullword
        $old_pdb = "Projects\\StrelaDLLCompile\\Release\\StrelaDLLCompile.pdb" fullword
    condition:
        3 of ($s*) or $old_pdb
}
