/*
 * windows/virus.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/windows/virus.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     3   Upstream files: 3
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Windows_Virus_Expiro.yar ----
rule Windows_Virus_Expiro_84e99ff0 {
    meta:
        author = "Elastic Security"
        id = "84e99ff0-bff3-4a9c-93fb-504a32cbc44d"
        fingerprint = "843182cbbf7ff65699001f074972d584c65bdb1e1d76210b44cf6ba06830253c"
        creation_date = "2023-09-26"
        last_modified = "2023-11-02"
        threat_name = "Windows.Virus.Expiro"
        reference_sample = "47107836ead700bddbe9e8a0c016b5b1443c785442b2addbb50a70445779bad7"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a1 = { 50 51 52 53 55 56 57 E8 00 00 00 00 5B 81 EB ?? ?? ?? 00 BA 00 00 00 00 53 81 }
        $a2 = { 81 C2 00 04 00 00 81 C3 00 04 00 00 }
    condition:
        all of them
}

// ---- Windows_Virus_Floxif.yar ----
rule Windows_Virus_Floxif_493d1897 {
    meta:
        author = "Elastic Security"
        id = "493d1897-864e-4f18-8511-0c6c9d990990"
        fingerprint = "6a043d05ca24846cfba28b5ea603a3e512a5af4f4e15629851a922190245ca1e"
        creation_date = "2023-09-26"
        last_modified = "2023-11-02"
        threat_name = "Windows.Virus.Floxif"
        reference_sample = "e628b7973ee25fdfd8f849fdf5923c6fba48141de802b0b4ce3e9ad2e40fe470"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a = { 8B 54 24 04 80 7A 03 01 75 04 8D 42 04 C3 8D 42 04 53 8B C8 8A 5A 02 84 DB 74 02 30 19 8A 19 }
    condition:
        all of them
}

// ---- Windows_Virus_Neshta.yar ----
rule Windows_Virus_Neshta_2a5a14c8 {
    meta:
        author = "Elastic Security"
        id = "2a5a14c8-27d8-4658-8941-0bb221d54ad3"
        fingerprint = "4ca7b0c908d08bf8b2041d7b41be8569efa54db99ebf04c7ff290c6bcad7dc02"
        creation_date = "2024-01-22"
        last_modified = "2024-02-08"
        threat_name = "Windows.Virus.Neshta"
        reference_sample = "f298214764ee9ab690cb4b376d8a7893edcd9c05a3c4e6f3a56010974a130bd7"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "windows"
    strings:
        $a1 = { 44 65 6C 70 68 69 2D 74 68 65 20 62 65 73 74 2E 20 46 75 63 6B 20 6F 66 66 20 61 6C 6C 20 74 68 65 20 72 65 73 74 2E 20 4E 65 73 68 74 61 20 31 2E 30 20 4D 61 64 65 20 69 6E 20 42 65 6C 61 72 75 73 2E }
        $a2 = { 55 8B EC 81 C4 64 FF FF FF 53 56 57 33 D2 89 95 64 FF FF FF 8B F8 33 C0 55 68 FC 6D 40 00 64 FF 30 64 89 20 8D 85 69 FF FF FF 50 68 97 00 00 00 E8 1B D3 FF FF 33 DB EB 5C 8B F3 81 E6 FF 00 00 }
    condition:
        any of them
}
