/*
 * linux/ransomware.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/linux/ransomware.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     28   Upstream files: 24
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Linux_Ransomware_Agenda.yar ----
rule Linux_Ransomware_Agenda_4562a654 {
    meta:
        author = "Elastic Security"
        id = "4562a654-a595-4480-a095-bd89ec907529"
        fingerprint = "b290b47e0839a5563b86d9d7dfbdc7fb2efa5669ede07f3710031f251b82ed6b"
        creation_date = "2024-09-12"
        last_modified = "2024-11-22"
        threat_name = "Linux.Ransomware.Agenda"
        reference_sample = "cd27a31e618fe93df37603e5ece3352a91f27671ee73bdc8ce9ad793cad72a0f"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $ = "%s_RECOVER.txt"
        $ = "-- Qilin"
        $ = "no-vm-kill"
        $ = "File extensions blacklist: [%s]"
    condition:
        3 of them
}

// ---- Linux_Ransomware_Akira.yar ----
rule Linux_Ransomware_Akira_02237952 {
    meta:
        author = "Elastic Security"
        id = "02237952-b9ac-44e5-a32f-f3cc8f28a89b"
        fingerprint = "7fcfac47be082441f6df149d0615a9d2020ac1e9023eabfcf10db4fe400cd474"
        creation_date = "2023-07-28"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Akira"
        reference_sample = "1d3b5c650533d13c81e325972a912e3ff8776e36e18bca966dae50735f8ab296"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "No path to encrypt" fullword
        $a2 = "--encryption_percent" fullword
        $a3 = "Failed to import public key" fullword
        $a4 = "akira_readme.txt" fullword
    condition:
        3 of them
}

rule Linux_Ransomware_Akira_27440619 {
    meta:
        author = "Elastic Security"
        id = "27440619-50de-4103-b961-6b66cf9001f9"
        fingerprint = "611b051982db94dc83a875b3e5ae20177690fda16ead5b8591cb12d0e899712b"
        creation_date = "2024-11-21"
        last_modified = "2024-11-22"
        threat_name = "Linux.Ransomware.Akira"
        reference_sample = "3298d203c2acb68c474e5fdad8379181890b4403d6491c523c13730129be3f75"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 41 83 A7 00 01 00 00 00 31 C0 41 88 87 04 01 00 00 6A 08 5B 49 89 9F 08 01 00 00 0F 57 C0 41 0F 29 87 10 01 00 00 49 89 9F 20 01 00 00 41 0F 11 87 28 01 00 00 41 C6 87 38 01 00 00 01 6A 01 41 5E }
    condition:
        all of them
}

// ---- Linux_Ransomware_Babuk.yar ----
rule Linux_Ransomware_Babuk_bd216cab {
    meta:
        author = "Elastic Security"
        id = "bd216cab-6532-4a71-9353-8ad692550b97"
        fingerprint = "c7517a40759de20edf7851d164c0e4ba71de049f8ea964f15ab5db12c35352ad"
        creation_date = "2024-05-09"
        last_modified = "2024-06-12"
        threat_name = "Linux.Ransomware.Babuk"
        reference_sample = "d305a30017baef4f08cee38a851b57869676e45c66e64bb7cc58d40bf0142fe0"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "Whole files count: %d"
        $a2 = "Doesn't encrypted files: %d"
    condition:
        all of them
}

// ---- Linux_Ransomware_BlackBasta.yar ----
rule Linux_Ransomware_BlackBasta_96eb3f20 {
    meta:
        author = "Elastic Security"
        id = "96eb3f20-9c40-4d40-8a6c-568a51c52d4d"
        fingerprint = "5146ad9def7ccaba4b4896f345b0950c587ad5f96a106ec461caeb028d809ead"
        creation_date = "2022-08-06"
        last_modified = "2022-08-16"
        threat_name = "Linux.Ransomware.BlackBasta"
        reference_sample = "96339a7e87ffce6ced247feb9b4cb7c05b83ca315976a9522155bad726b8e5be"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "Done time: %.4f seconds, encrypted: %.4f gb" ascii fullword
        $a2 = "Your data are stolen and encrypted" ascii fullword
        $a3 = "fileEncryptionPercent" ascii fullword
        $a4 = "fileQueueLocker" ascii fullword
        $a5 = "totalBytesEncrypted" ascii fullword
        $seq_encrypt_block = { 41 56 31 D2 41 55 41 54 49 89 FE 55 53 48 89 F5 49 63 D8 4C }
        $seq_encrypt_thread = { 4C 8B 74 24 ?? 31 DB 45 31 FF 4D 8B 6E ?? 49 83 FD ?? 0F 87 ?? ?? ?? ?? 31 C0 4D 39 EF 0F 82 ?? ?? ?? ?? 48 01 C3 4C 39 EB 0F 83 ?? ?? ?? ?? }
    condition:
        3 of ($a*) and 1 of ($seq*)
}

// ---- Linux_Ransomware_BlackSuit.yar ----
rule Linux_Ransomware_BlackSuit_9f53e7e5 {
    meta:
        author = "Elastic Security"
        id = "9f53e7e5-7177-4e17-ac12-9214c4deddf2"
        fingerprint = "34355cb1731fe6c8fa684a484943127f8fdf3814d45025e29bdf25a08b4890fd"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.BlackSuit"
        reference_sample = "1c849adcccad4643303297fb66bfe81c5536be39a87601d67664af1d14e02b9e"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "esxcli vm process list > list_" fullword
        $a2 = "Drop readme failed: %s(%d)" fullword
        $a3 = "README.BlackSuit.txt" fullword
    condition:
        2 of them
}

// ---- Linux_Ransomware_Clop.yar ----
rule Linux_Ransomware_Clop_728cf32a {
    meta:
        author = "Elastic Security"
        id = "728cf32a-94c1-4979-b092-6851649946be"
        fingerprint = "86644f9f1e9f0b69896cd05ae1442a3b99483cc0ff15773c0c3403e59b6d5c97"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Clop"
        reference_sample = "09d6dab9b70a74f61c41eaa485b37de9a40c86b6d2eae7413db11b4e6a8256ef"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "CONTACT US BY EMAIL:"
        $a2 = "OR WRITE TO THE CHAT AT->"
        $a3 = "(use TOR browser)"
        $a4 = ".onion/"
    condition:
        3 of them
}

// ---- Linux_Ransomware_Conti.yar ----
rule Linux_Ransomware_Conti_a89c26cf {
    meta:
        author = "Elastic Security"
        id = "a89c26cf-ccec-40ca-85d3-d014b767fd6a"
        fingerprint = "c29bb1bbbd76712bbc3ddd1dfeeec40b230677339dea7441b1f34159ccbbdf9f"
        creation_date = "2023-07-30"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Conti"
        reference_sample = "95776f31cbcac08eb3f3e9235d07513a6d7a6bf9f1b7f3d400b2cf0afdb088a7"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "paremeter --size cannot be %d" fullword
        $a2 = "--vmkiller" fullword
        $a3 = ".conti" fullword
        $a4 = "Cannot create file vm-list.txt" fullword
    condition:
        3 of them
}

// ---- Linux_Ransomware_EchoRaix.yar ----
rule Linux_Ransomware_EchoRaix_ea9532df {
    meta:
        author = "Elastic Security"
        id = "ea9532df-1136-4b11-bf4f-8838074f4e66"
        fingerprint = "f28b340b99ec2b96ee78da50b3fc455c87dca1e898abf008c16ac192556939c5"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.EchoRaix"
        reference_sample = "dfe32d97eb48fb2afc295eecfda3196cba5d27ced6217532d119a764071c6297"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 43 58 68 64 4B 74 7A 65 42 59 6C 48 65 58 79 5A 52 62 61 30 2F 6E 65 46 7A 34 49 7A 67 53 38 4C 68 75 36 38 5A 75 4C 4C 52 2F 66 67 6E 72 34 79 54 72 5A 54 6B 43 36 31 62 2D 59 6F 6C 49 2F 32 4C 36 66 53 55 46 52 72 55 70 49 34 6D 4E 53 41 4F 62 5F }
    condition:
        all of them
}

rule Linux_Ransomware_EchoRaix_ee0c719a {
    meta:
        author = "Elastic Security"
        id = "ee0c719a-1f04-45ff-9e49-38028b138fd0"
        fingerprint = "073d62ce55b1940774ffadeb5b76343aa49bd0a36cf82d50e2bae44f6049a1e8"
        creation_date = "2023-07-29"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.EchoRaix"
        reference_sample = "e711b2d9323582aa390cf34846a2064457ae065c7d2ee1a78f5ed0859b40f9c0"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = { 24 10 89 44 24 68 8B 4C 24 14 8B 54 24 18 85 C9 74 57 74 03 8B }
        $a2 = { 6D 61 69 6E 2E 43 68 65 63 6B 49 73 52 75 6E 6E 69 6E 67 }
    condition:
        all of them
}

// ---- Linux_Ransomware_Erebus.yar ----
rule Linux_Ransomware_Erebus_ead4f55b {
    meta:
        author = "Elastic Security"
        id = "ead4f55b-a4c6-46ff-bc8e-03831a17df9c"
        fingerprint = "571832cc76322a95244b042ab9b358755a1be19260410658dc32c03c5cae7638"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Erebus"
        reference_sample = "6558330f07a7c90c40006346ed09e859b588d031193f8a9679fe11a85c8ccb37"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "important files have been encrypted"
        $a2 = "max_size_mb"
        $a3 = "EREBUS IS BEST."
    condition:
        2 of them
}

// ---- Linux_Ransomware_Esxiargs.yar ----
rule Linux_Ransomware_Esxiargs_75a8ec04 {
    meta:
        author = "Elastic Security"
        id = "75a8ec04-c41d-4702-94fa-976870762aaf"
        fingerprint = "279259c7ca41331b09842c2221139d249d6dfe2e2cb6b27eb50af7be75120ce4"
        creation_date = "2023-02-09"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Esxiargs"
        reference_sample = "11b1b2375d9d840912cfd1f0d0d04d93ed0cddb0ae4ddb550a5b62cd044d6b66"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $s1 = "number of MB in encryption block"
        $s2 = "number of MB to skip while encryption"
        $s3 = "get_pk_data: key file is empty"
        $s4 = { 6F 70 65 6E 00 6C 73 65 65 6B 20 5B 65 6E 64 5D 00 6F 70 65 6E 5F 70 6B 5F 66 69 6C 65 }
        $s5 = "[<enc_step>] [<enc_size>] [<file_size>]"
    condition:
        3 of them
}

// ---- Linux_Ransomware_Gonnacry.yar ----
rule Linux_Ransomware_Gonnacry_53c3832d {
    meta:
        author = "Elastic Security"
        id = "53c3832d-ceff-407d-920b-7b6442688fa9"
        fingerprint = "7d93c26c9e069af5cef964f5747104ba6d1d0d030a1f6b1c377355223c5359a1"
        creation_date = "2021-01-12"
        last_modified = "2021-09-16"
        threat_name = "Linux.Ransomware.Gonnacry"
        reference_sample = "f5de75a6db591fe6bb6b656aa1dcfc8f7fe0686869c34192bfa4ec092554a4ac"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 55 48 89 E5 48 83 EC 10 48 89 7D F8 EB 56 48 8B 45 F8 48 8B }
    condition:
        all of them
}

// ---- Linux_Ransomware_Hellokitty.yar ----
rule Linux_Ransomware_Hellokitty_35731270 {
    meta:
        author = "Elastic Security"
        id = "35731270-b283-4dff-8316-6a541ff1d4d5"
        fingerprint = "1945bfcbe084f8f6671c73e74679fb2933d2ebea54479fdf348d4804a614279a"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Hellokitty"
        reference_sample = "556e5cb5e4e77678110961c8d9260a726a363e00bf8d278e5302cb4bfccc3eed"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "File Locked:%s PID:%d" fullword
        $a2 = "error encrypt: %s rename back:%s" fullword
        $a3 = "esxcli vm process kill -t=soft -w=%d" fullword
    condition:
        2 of them
}

// ---- Linux_Ransomware_Hive.yar ----
rule Linux_Ransomware_Hive_bdc7de59 {
    meta:
        author = "Elastic Security"
        id = "bdc7de59-bf12-461f-99e0-ec2532ace4e9"
        fingerprint = "415ef589a1c2da6b16ab30fb68f938a9ee7917f5509f73aa90aeec51c10dc1ff"
        creation_date = "2022-01-05"
        last_modified = "2022-01-26"
        threat_name = "Linux.Ransomware.Hive"
        reference_sample = "713b699c04f21000fca981e698e1046d4595f423bd5741d712fd7e0bc358c771"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 40 03 4C 39 C1 73 3A 4C 89 84 24 F0 00 00 00 48 89 D3 48 89 CF 4C }
    condition:
        all of them
}

// ---- Linux_Ransomware_ItsSoEasy.yar ----
rule Linux_Ransomware_ItsSoEasy_30bd68e0 {
    meta:
        author = "Elastic Security"
        id = "30bd68e0-3050-4aaf-b1bb-3ae10b6bd6dd"
        fingerprint = "33170bbe6d182b36c77d732c283377f6f84cf82bd8d28cc4c3aef4d0914a0ae8"
        creation_date = "2023-07-28"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.ItsSoEasy"
        reference_sample = "efb1024654e86c0c30d2ac5f97d27f5f27b4dd3f7f6ada65d58691f0d703461c"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = { 6D 61 69 6E 2E 65 6E 63 72 79 70 74 44 61 74 61 2E 66 75 6E 63 31 }
        $a2 = { 6D 61 69 6E 2E 6D 61 6B 65 41 75 74 6F 52 75 6E }
    condition:
        all of them
}

// ---- Linux_Ransomware_LimpDemon.yar ----
rule Linux_Ransomware_LimpDemon_95c748e0 {
    meta:
        author = "Elastic Security"
        id = "95c748e0-e2f5-4997-a69d-dbc8885e6f18"
        fingerprint = "20527c2e0d2e577c17da7184193ba372027cedb075f78bb75aff9d218c2d660b"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.LimpDemon"
        reference_sample = "a4200e90a821a2f2eb3056872f06cf5b057be154dcc410274955b2aaca831651"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "[-] You have to pass access key to start process" fullword
        $a2 = "[+] Shutting down VMWare ESXi servers..." fullword
        $a3 = "%s --daemon (start as a service)" fullword
        $a4 = "%s --access-key <key> (key for decryption config)" fullword
    condition:
        2 of them
}

// ---- Linux_Ransomware_Lockbit.yar ----
rule Linux_Ransomware_Lockbit_d248e80e {
    meta:
        author = "Elastic Security"
        id = "d248e80e-3e2f-4957-adc3-0c912b0cd386"
        fingerprint = "417ecf5a0b6030ed5b973186efa1e72dfa56886ba6cfc5fbf615e0814c24992f"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Lockbit"
        reference_sample = "4800a67ceff340d2ab4f79406a01f58e5a97d589b29b35394b2a82a299b19745"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "restore-my-files.txt" fullword
        $b1 = "xkeyboard-config" fullword
        $b2 = "bootsect.bak" fullword
        $b3 = "lockbit" fullword
        $b4 = "Error: %s" fullword
        $b5 = "crypto_generichash_blake2b_final" fullword
    condition:
        $a1 and 2 of ($b*)
}

rule Linux_Ransomware_Lockbit_5b30a04b {
    meta:
        author = "Elastic Security"
        id = "5b30a04b-d618-4698-a797-30bf6d4a001c"
        fingerprint = "99bf6afb1554ec3b3b82389c93ca87018c51f7a80270d64007a5f5fc59715c45"
        creation_date = "2023-07-29"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Lockbit"
        reference_sample = "41cbb7d79388eaa4d6e704bd4a8bf8f34d486d27277001c343ea3ce112f4fb0d"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = { 5D 50 4A 49 55 58 40 77 58 54 5C }
        $a2 = { 33 6B 5C 5A 4C 4B 4A 50 4F 5C 55 40 }
        $a3 = { 5E 4C 58 4B 58 57 4D 5C 5C 5D }
    condition:
        all of them
}

rule Linux_Ransomware_Lockbit_4a497d53 {
    meta:
        author = "Elastic Security"
        id = "4a497d53-3e96-49b2-abb3-098c4a87267e"
        fingerprint = "f0f55b9fc3f46724a96d90db45346fb104227480b902ed3054e002f725475d69"
        creation_date = "2025-01-09"
        last_modified = "2026-05-22"
        threat_name = "Linux.Ransomware.Lockbit"
        reference_sample = "a60acd0adeccbe29ff8402db0e974eba25c9acf98a3af98940e518d465fb1bbe"
        severity = 100
        arch_context = "x86, arm64"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 24 B3 A0 E1 40 70 8D E5 44 50 8D E5 40 80 89 E2 00 70 A0 E3 50 50 8D E2 0B 00 57 E1 }
    condition:
        all of them
}

// ---- Linux_Ransomware_Monti.yar ----
rule Linux_Ransomware_Monti_9c64f016 {
    meta:
        author = "Elastic Security"
        id = "9c64f016-0fd9-41bf-8916-cdf3a35efdd6"
        fingerprint = "af28cc97eed328f3b2b0181784545e41a521e9dfff09a504177cb56929606b84"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Monti"
        reference_sample = "ad8d1b28405d9aebae6f42db1a09daec471bf342e9e0a10ab4e0a258a7fa8713"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "[%s] Flag doesn't equal MONTI."
        $a2 = "--vmkill Whether to kill the virtual machine"
        $a3 = "MONTI strain."
        $a4 = "http://monti"
    condition:
        2 of them
}

// ---- Linux_Ransomware_NoEscape.yar ----
rule Linux_Ransomware_NoEscape_6de58e0c {
    meta:
        author = "Elastic Security"
        id = "6de58e0c-67f9-4344-9fe9-26bfc37e537e"
        fingerprint = "60a160abcbb6d93d9ee167663e419047f3297d549c534cbe66d035a0aa36d806"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.NoEscape"
        reference_sample = "46f1a4c77896f38a387f785b2af535f8c29d40a105b63a259d295cb14d36a561"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "HOW_TO_RECOVER_FILES.txt"
        $a2 = "large_file_size_mb"
        $a3 = "note_text"
    condition:
        all of them
}

// ---- Linux_Ransomware_Quantum.yar ----
rule Linux_Ransomware_Quantum_8513fb8b {
    meta:
        author = "Elastic Security"
        id = "8513fb8b-43f7-46b1-8318-5549a7609d3b"
        fingerprint = "1c1af76ab5df8243b8e25555f1762749ca60da56fecea9d4131c612358244525"
        creation_date = "2023-07-28"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.Quantum"
        reference_sample = "3bcb9ad92fdca53195f390fc4d8d721b504b38deeda25c1189a909a7011406c9"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "All your files are encrypted on all devices across the network"
        $a2 = "process with pid %d is blocking %s, going to kill it"
    condition:
        all of them
}

// ---- Linux_Ransomware_RagnarLocker.yar ----
rule Linux_Ransomware_RagnarLocker_9f5982b8 {
    meta:
        author = "Elastic Security"
        id = "9f5982b8-98db-42d1-b987-451d3cb7fc4b"
        fingerprint = "782d9225a6060c23484a285f7492bb45f21c37597ea82e4ca309aedbb1c30223"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.RagnarLocker"
        reference_sample = "f668f74d8808f5658153ff3e6aee8653b6324ada70a4aa2034dfa20d96875836"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = ".README_TO_RESTORE"
        $a2 = "If WE MAKE A DEAL:"
        $a3 = "Unable to rename file from: %s to: %s"
    condition:
        2 of them
}

// ---- Linux_Ransomware_RedAlert.yar ----
rule Linux_Ransomware_RedAlert_39642d52 {
    meta:
        author = "Elastic Security"
        id = "39642d52-0a4b-48d5-bb62-8f37beb4dc6a"
        fingerprint = "744524ee2ae9e3e232f15b0576cdab836ac0fe3c9925eab66ed8c6b0be3f23d7"
        creation_date = "2022-07-06"
        last_modified = "2022-08-16"
        threat_name = "Linux.Ransomware.RedAlert"
        reference_sample = "039e1765de1cdec65ad5e49266ab794f8e5642adb0bdeb78d8c0b77e8b34ae09"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $str_ransomnote = "\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\% REDALERT UNIQUE IDENTIFIER START \\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%\\%" ascii fullword
        $str_print = "\t\t\t########\n\t\t\t[ N13V ]\n\t\t\t########\n\n" ascii fullword
        $str_arg = "[info] Catch -t argument. Check encryption time" ascii fullword
        $str_ext = ".crypt658" ascii fullword
        $byte_checkvm = { 48 8B 14 DD ?? ?? ?? ?? 31 C0 48 83 C9 FF FC 48 89 EE 48 89 D7 F2 AE 4C 89 E7 48 F7 D1 E8 }
    condition:
        3 of ($str_*) or ($byte_checkvm and $str_print)
}

// ---- Linux_Ransomware_RoyalPest.yar ----
rule Linux_Ransomware_RoyalPest_502a3db6 {
    meta:
        author = "Elastic Security"
        id = "502a3db6-4711-42c7-8178-c3150f184fc6"
        fingerprint = "4bde7998f41ef3d0f2769078cf56e03d36eacf503f859a23fc442ced95d839cb"
        creation_date = "2023-07-27"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.RoyalPest"
        reference_sample = "09a79e5e20fa4f5aae610c8ce3fe954029a91972b56c6576035ff7e0ec4c1d14"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = "hit by Royal ransomware."
        $a2 = "Please contact us via :"
        $a3 = ".onion/%s"
        $a4 = "esxcli vm process list > list"
    condition:
        3 of them
}

// ---- Linux_Ransomware_SFile.yar ----
rule Linux_Ransomware_SFile_9e347b52 {
    meta:
        author = "Elastic Security"
        id = "9e347b52-233a-4956-9f1f-7600c482e280"
        fingerprint = "094af0030d51d1e28405fc02a51ccc1bedf9e083b3d24b82c36f4b397eefbb0b"
        creation_date = "2023-07-29"
        last_modified = "2024-02-13"
        threat_name = "Linux.Ransomware.SFile"
        reference_sample = "49473adedc4ee9b1252f120ad8a69e165dc62eabfa794370408ae055ec65db9d"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a1 = { 49 74 27 73 20 6A 75 73 74 20 61 20 62 75 73 69 6E 65 73 73 2E }
        $a2 = { 41 6C 6C 20 64 61 74 61 20 69 73 20 70 72 6F 70 65 72 6C 79 20 70 72 6F 74 65 63 74 65 64 20 61 67 61 69 6E 73 74 20 75 6E 61 75 74 68 6F 72 69 7A 65 64 20 61 63 63 65 73 73 20 62 79 20 73 74 65 61 64 79 20 65 6E 63 72 79 70 74 69 6F 6E 20 74 65 63 68 6E 6F 6C 6F 67 79 2E }
    condition:
        all of them
}

// ---- Linux_Ransomware_Sodinokibi.yar ----
rule Linux_Ransomware_Sodinokibi_2883d7cd {
    meta:
        author = "Elastic Security"
        id = "2883d7cd-fd3b-47a5-9283-a40335172c62"
        fingerprint = "d6570a8e9358cef95388a72b2e7f747ee5092620c4f92a4b4e6c1bb277e1cb36"
        creation_date = "2022-01-05"
        last_modified = "2022-01-26"
        threat_name = "Linux.Ransomware.Sodinokibi"
        reference_sample = "a322b230a3451fd11dcfe72af4da1df07183d6aaf1ab9e062f0e6b14cf6d23cd"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 85 08 FF FF FF 48 01 85 28 FF FF FF 48 8B 85 08 FF FF FF 48 29 85 20 FF }
    condition:
        all of them
}
