/*
 * linux/virus.yar
 * Generated by tools/build_rules.py - do not edit by hand.
 *
 * sigurl:    https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules/linux/virus.yar
 * Source:    https://github.com/elastic/protections-artifacts.git
 * Commit:    9c334cf8298d9ff7e19c2a50817669072abc2d66
 * Generated: 2026-08-31
 * Rules:     5   Upstream files: 4
 *
 * Upstream rules are licensed under the Elastic License 2.0.
 * See LICENSE-NOTICE.md. Rules are redistributed unmodified.
 */

// ---- Linux_Virus_Gmon.yar ----
rule Linux_Virus_Gmon_e544d891 {
    meta:
        author = "Elastic Security"
        id = "e544d891-3f6d-4da2-be86-e4ab58c66465"
        fingerprint = "269f0777f846f9fc8fe56ea7436bddb155cde8c9a4bf9070f46db0081caef718"
        creation_date = "2021-01-12"
        last_modified = "2021-09-16"
        threat_name = "Linux.Virus.Gmon"
        reference_sample = "d0fe377664aa0bc0d1fd3a307650f211dd3ef2e2f04597abee465e836e6a6f32"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { E5 53 51 52 8B 44 24 14 8B 5C 24 18 8B 4C 24 1C 8B 54 24 20 }
    condition:
        all of them
}

rule Linux_Virus_Gmon_192bd9b3 {
    meta:
        author = "Elastic Security"
        id = "192bd9b3-230a-4f07-b4f9-06213a6b6f47"
        fingerprint = "532055052554ed9a38b16f764d3fbae0efd333f5b2254b9a1e3f6d656d77f1e4"
        creation_date = "2021-01-12"
        last_modified = "2021-09-16"
        threat_name = "Linux.Virus.Gmon"
        reference_sample = "d0fe377664aa0bc0d1fd3a307650f211dd3ef2e2f04597abee465e836e6a6f32"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { E5 56 53 8B 75 08 8B 5D 0C 8B 4D 10 31 D2 39 CA 7D 11 8A 04 1A 38 }
    condition:
        all of them
}

// ---- Linux_Virus_Rst.yar ----
rule Linux_Virus_Rst_1214e2ae {
    meta:
        author = "Elastic Security"
        id = "1214e2ae-90e4-425e-b47f-0a0981623236"
        fingerprint = "a13a9825815a417be991db57f80dac4d0c541e303e4a4e6bd03c46ece73703ea"
        creation_date = "2021-04-06"
        last_modified = "2021-09-16"
        threat_name = "Linux.Virus.Rst"
        reference_sample = "b0e4f44d2456960bb6b20cb468c4ca1390338b83774b7af783c3d03e49eebe44"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 00 00 00 53 89 F3 CD 80 5B 58 5F 5E 5A 59 5B C3 }
    condition:
        all of them
}

// ---- Linux_Virus_Staffcounter.yar ----
rule Linux_Virus_Staffcounter_d2d608a8 {
    meta:
        author = "Elastic Security"
        id = "d2d608a8-2d65-4b10-be71-0a0a6a027920"
        fingerprint = "a791024dc3064ed2e485e5c57d7ab77fc1ec14665c9302b8b572ac4d9d5d2f93"
        creation_date = "2021-06-28"
        last_modified = "2021-09-16"
        threat_name = "Linux.Virus.Staffcounter"
        reference = "06e562b54b7ee2ffee229c2410c9e2c42090e77f6211ce4b9fa26459ff310315"
        severity = "100"
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 20 22 00 20 4C 69 6E 75 78 22 20 3C 00 54 6F 3A 20 22 00 20 }
    condition:
        all of them
}

// ---- Linux_Virus_Thebe.yar ----
rule Linux_Virus_Thebe_1eb5985a {
    meta:
        author = "Elastic Security"
        id = "1eb5985a-2b35-434f-81d9-f502dff25397"
        fingerprint = "5cf9aa9a31c36028025d5038c98d56aef32c9e8952aa5cd4152fbd811231769e"
        creation_date = "2021-04-06"
        last_modified = "2021-09-16"
        threat_name = "Linux.Virus.Thebe"
        reference_sample = "30af289be070f4e0f8761f04fb44193a037ec1aab9cc029343a1a1f2a8d67670"
        severity = 100
        arch_context = "x86"
        scan_context = "file, memory"
        license = "Elastic License v2"
        os = "linux"
    strings:
        $a = { 42 31 C9 31 DB 31 F6 B0 1A CD 80 85 C0 0F 85 83 }
    condition:
        all of them
}
