#!/usr/bin/env python3
"""
Build focused, individually-addressable YARA rule files from
elastic/protections-artifacts, laid out for on-demand scanning.

Output:
  rules/<platform>/<category>.yar   focused set, e.g. rules/linux/ransomware.yar
  rules/<platform>/_all.yar         every rule for that platform + the Multi_* rules
  rules/INDEX.md                    catalogue with rule counts and sigurl values

Each file is fetched directly by URL via the yara_file / yara_process tables.
osquery matches signature_urls by exact host+scheme and treats the PATH as a
regex, so one allowlist entry covers this whole tree.

Deterministic: the same upstream commit produces byte-identical output.
"""
import argparse, hashlib, os, re, subprocess, sys, tempfile
from datetime import datetime, timezone

UPSTREAM = "https://github.com/elastic/protections-artifacts.git"
RULES_SUBDIR = os.path.join("yara", "rules")
PLATFORMS = ("macos", "linux", "windows", "multi")
RULE_RE = re.compile(r"^\s*rule\s+([A-Za-z_]\w*)", re.M)
IMPORT_RE = re.compile(r'^\s*import\s+"([a-z]+)"', re.M)


def sh(*a):
    return subprocess.run(a, check=True, capture_output=True, text=True).stdout.strip()


def fetch(workdir):
    dest = os.path.join(workdir, "upstream")
    if not os.path.isdir(dest):
        sh("git", "clone", "--depth", "1", "--filter=blob:none", "--sparse", "-q", UPSTREAM, dest)
        sh("git", "-C", dest, "sparse-checkout", "set", "yara")
    return os.path.join(dest, RULES_SUBDIR), sh("git", "-C", dest, "rev-parse", "HEAD")


def split_name(fn):
    """MacOS_Trojan_Generic.yar -> ('macos', 'trojan'). Returns None if unknown."""
    parts = fn[:-4].split("_")
    if len(parts) < 2:
        return None
    plat, cat = parts[0].lower(), parts[1].lower()
    if plat not in PLATFORMS or not cat.isalnum():
        return None
    return plat, cat


def header(rel, sha, stamp, nrules, nfiles, base_url):
    return (
        "/*\n"
        " * %s\n"
        " * Generated by tools/build_rules.py - do not edit by hand.\n"
        " *\n"
        " * sigurl:    %s/%s\n"
        " * Source:    %s\n"
        " * Commit:    %s\n"
        " * Generated: %s\n"
        " * Rules:     %d   Upstream files: %d\n"
        " *\n"
        " * Upstream rules are licensed under the Elastic License 2.0.\n"
        " * See LICENSE-NOTICE.md. Rules are redistributed unmodified.\n"
        " */\n\n" % (rel, base_url, rel, UPSTREAM, sha, stamp, nrules, nfiles)
    )


def emit(path, rel, chunks, sha, stamp, base_url):
    seen, kept, nrules, imports = set(), [], 0, set()
    for fn, body in chunks:
        names = RULE_RE.findall(body)
        if any(n in seen for n in names):
            continue
        seen.update(names)
        nrules += len(names)
        imports.update(IMPORT_RE.findall(body))
        kept.append("// ---- %s ----\n%s\n" % (fn, body.rstrip()))
    text = header(rel, sha, stamp, nrules, len(kept), base_url) + "\n".join(kept)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return {"rules": nrules, "files": len(kept), "bytes": len(text.encode()),
            "imports": sorted(imports), "sha256": hashlib.sha256(text.encode()).hexdigest()}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="rules")
    ap.add_argument("--work", default=None)
    ap.add_argument("--base-url",
                    default="https://raw.githubusercontent.com/karmine05/gitops-yara/main/rules")
    ap.add_argument("--verify", action="store_true")
    a = ap.parse_args()

    work = a.work or tempfile.mkdtemp(prefix="yb-")
    os.makedirs(work, exist_ok=True)
    out = os.path.abspath(a.out)
    src, sha = fetch(work)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    buckets, skipped = {}, []
    for fn in sorted(os.listdir(src)):
        if not fn.endswith(".yar"):
            continue
        pc = split_name(fn)
        if not pc:
            skipped.append(fn)
            continue
        body = open(os.path.join(src, fn), encoding="utf-8", errors="replace").read()
        buckets.setdefault(pc, []).append((fn, body))

    multi = [c for (p, _), cs in buckets.items() if p == "multi" for c in cs]
    report = {}
    for (plat, cat), chunks in sorted(buckets.items()):
        rel = "%s/%s.yar" % (plat, cat)
        report[rel] = emit(os.path.join(out, rel), rel, chunks, sha, stamp, a.base_url)

    for plat in PLATFORMS:
        own = [c for (p, _), cs in sorted(buckets.items()) if p == plat for c in cs]
        if not own:
            continue
        combined = own if plat == "multi" else own + multi
        rel = "%s/_all.yar" % plat
        report[rel] = emit(os.path.join(out, rel), rel, combined, sha, stamp, a.base_url)

    lines = ["# Rule index", "",
             "Builds rules from `%s` @ `%s`, %s." % (UPSTREAM, sha[:12], stamp), "",
             "Pass any `sigurl` below to `yara_file` or `yara_process`. One allowlist",
             "entry in agent options covers this whole tree.", ""]
    for plat in PLATFORMS:
        rels = sorted(r for r in report if r.startswith(plat + "/"))
        if not rels:
            continue
        lines += ["## %s" % plat, "", "| File | Rules | Size | sigurl |", "|---|---:|---:|---|"]
        for r in rels:
            m = report[r]
            lines.append("| `%s` | %d | %d KB | `%s/%s` |" % (r, m["rules"], m["bytes"] // 1024, a.base_url, r))
        lines.append("")
    with open(os.path.join(out, "INDEX.md"), "w") as fh:
        fh.write("\n".join(lines))

    with open(os.path.join(out, "MANIFEST.txt"), "w") as fh:
        fh.write("upstream %s\ncommit   %s\nbuilt    %s\n\n" % (UPSTREAM, sha, stamp))
        for r in sorted(report):
            m = report[r]
            fh.write("%s\n  rules %d  files %d  bytes %d\n  sha256 %s\n"
                     % (r, m["rules"], m["files"], m["bytes"], m["sha256"]))

    allimp = sorted({i for m in report.values() for i in m["imports"]})
    print("upstream %s" % sha)
    print("%d rule files" % len(report))
    print("module imports across all files: %s" % (", ".join(allimp) or "(none)"))
    if skipped:
        print("skipped %d unrecognised upstream files: %s" % (len(skipped), skipped[:3]))

    if a.verify:
        try:
            import yara
        except ImportError:
            print("!! yara-python missing - skipping compile check", file=sys.stderr)
            return
        bad = 0
        for r in sorted(report):
            try:
                yara.compile(filepath=os.path.join(out, r))
            except Exception as e:
                bad += 1
                print("COMPILE FAIL %s: %s" % (r, e), file=sys.stderr)
        print("compile check: %d/%d OK" % (len(report) - bad, len(report)))
        if bad:
            sys.exit(1)


if __name__ == "__main__":
    main()
