#!/usr/bin/env python3
"""
Build per-platform YARA bundles from elastic/protections-artifacts.

Two consumption tiers:
  yara_events  (macOS, Linux)   -> local files deployed by deploy/install-*.sh
  yara_file    (all platforms)  -> fetched over HTTPS via signature_urls + sigurl

Deterministic: the same upstream commit always produces byte-identical bundles.
Run with --verify to compile-check output (needs yara-python).
"""
import argparse, hashlib, os, re, subprocess, sys, tempfile
from datetime import datetime, timezone

UPSTREAM = "https://github.com/elastic/protections-artifacts.git"
RULES_SUBDIR = os.path.join("yara", "rules")

# file-name prefix -> bundle. Multi_* is cross-platform and is appended to all three.
GROUPS = {
    "macos":   ("macos-file-events.yar",   ("macos_",)),
    "linux":   ("linux-file-events.yar",   ("linux_",)),
    "windows": ("windows-ondemand.yar",    ("windows_",)),
}
MULTI_PREFIX = "multi_"

RULE_RE = re.compile(r"^\s*rule\s+([A-Za-z_]\w*)", re.M)
IMPORT_RE = re.compile(r'^\s*import\s+"([a-z]+)"', re.M)
SCAN_CTX_RE = re.compile(r'^\s*scan_context\s*=\s*"([^"]*)"', re.M)


def sh(*a, **kw):
    return subprocess.run(a, check=True, capture_output=True, text=True, **kw).stdout.strip()


def fetch(workdir):
    """Clone upstream shallow. Returns (rules_path, commit_sha)."""
    dest = os.path.join(workdir, "upstream")
    if not os.path.isdir(dest):
        sh("git", "clone", "--depth", "1", "--filter=blob:none", "--sparse", "-q", UPSTREAM, dest)
        sh("git", "-C", dest, "sparse-checkout", "set", "yara")
    sha = sh("git", "-C", dest, "rev-parse", "HEAD")
    return os.path.join(dest, RULES_SUBDIR), sha


def classify(filename):
    low = filename.lower()
    if low.startswith(MULTI_PREFIX):
        return list(GROUPS)                       # Multi_* lands in every bundle
    for group, (_, prefixes) in GROUPS.items():
        if any(low.startswith(p) for p in prefixes):
            return [group]
    return []


def build(rules_dir, out_dir, sha, stamp):
    buckets = {g: [] for g in GROUPS}
    for fn in sorted(os.listdir(rules_dir)):        # sorted => deterministic
        if not fn.endswith(".yar"):
            continue
        body = open(os.path.join(rules_dir, fn), encoding="utf-8", errors="replace").read()
        for g in classify(fn):
            buckets[g].append((fn, body))

    os.makedirs(out_dir, exist_ok=True)
    report = {}
    for group, (outname, _) in GROUPS.items():
        seen, chunks, nrules, imports, memory_only = set(), [], 0, set(), 0
        for fn, body in buckets[group]:
            names = RULE_RE.findall(body)
            if any(n in seen for n in names):       # duplicate rule name would fail to compile
                continue
            seen.update(names)
            nrules += len(names)
            imports.update(IMPORT_RE.findall(body))
            memory_only += sum(1 for c in SCAN_CTX_RE.findall(body) if c.strip() == "memory")
            chunks.append("// ---- %s ----\n%s\n" % (fn, body.rstrip()))

        header = (
            "/*\n"
            " * %s\n"
            " * Generated by tools/build_bundles.py - do not edit by hand.\n"
            " *\n"
            " * Source:    %s\n"
            " * Commit:    %s\n"
            " * Generated: %s\n"
            " * Rules:     %d   Files: %d\n"
            " *\n"
            " * Upstream rules are licensed under the Elastic License 2.0.\n"
            " * See LICENSE-NOTICE.md. Rules are redistributed unmodified.\n"
            " */\n\n" % (outname, UPSTREAM, sha, stamp, nrules, len(chunks))
        )
        text = header + "\n".join(chunks)
        with open(os.path.join(out_dir, outname), "w", encoding="utf-8") as fh:
            fh.write(text)
        report[group] = {
            "file": outname, "rules": nrules, "files": len(chunks),
            "bytes": len(text.encode()), "imports": sorted(imports),
            "memory_only_rules": memory_only,
            "sha256": hashlib.sha256(text.encode()).hexdigest(),
        }
    return report


def verify(out_dir, report):
    try:
        import yara
    except ImportError:
        print("!! yara-python not installed - skipping compile check", file=sys.stderr)
        print("   pip install yara-python", file=sys.stderr)
        return True
    ok = True
    for group, r in report.items():
        path = os.path.join(out_dir, r["file"])
        try:
            rules = yara.compile(filepath=path)
            n = sum(1 for _ in rules)
            print("   compile OK  %-28s %d rules loaded" % (r["file"], n))
        except Exception as e:
            ok = False
            print("   COMPILE FAIL %s: %s" % (r["file"], e), file=sys.stderr)
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "rules"))
    ap.add_argument("--work", default=None, help="cache dir for the upstream clone")
    ap.add_argument("--verify", action="store_true")
    a = ap.parse_args()

    work = a.work or tempfile.mkdtemp(prefix="yarabuild-")
    os.makedirs(work, exist_ok=True)
    out = os.path.abspath(a.out)

    rules_dir, sha = fetch(work)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    print("upstream commit %s" % sha)
    report = build(rules_dir, out, sha, stamp)

    print("\n%-28s%7s%7s%7s  imports" % ("bundle", "rules", "files", "MB"))
    for g, r in report.items():
        print("%-28s%7d%7d%7.2f  %s" % (r["file"], r["rules"], r["files"],
              r["bytes"] / 1e6, ",".join(r["imports"]) or "(none)"))

    if a.verify:
        print("\ncompile check:")
        if not verify(out, report):
            sys.exit(1)

    with open(os.path.join(out, "MANIFEST.txt"), "w") as fh:
        fh.write("upstream %s\ncommit   %s\nbuilt    %s\n\n" % (UPSTREAM, sha, stamp))
        for g, r in sorted(report.items()):
            fh.write("%s\n  rules %d  files %d  bytes %d\n  sha256 %s\n"
                     % (r["file"], r["rules"], r["files"], r["bytes"], r["sha256"]))
    print("\nwrote %s/MANIFEST.txt" % out)


if __name__ == "__main__":
    main()
